import { PageTitle, Section, P, Key, Callout, Bullets, Steps, Defs, DocLink, AppLink, Term } from "@/components/docs/prose";
import { DocFigure } from "@/components/docs/DocFigure";
import { ExampleDownloads } from "@/components/docs/ExampleDownloads";

export default function Guide() { return <>
<PageTitle lead="Ask one question per comparison and preserve the evidence needed to attribute the difference.">Experiments &amp; comparison</PageTitle>
<Section id="what-an-experiment-is" title="Choose the question first"><P>Baseline versus disruption estimates the disruption's impact. Disruption without a buffer versus the same disruption with a buffer estimates the buffer's effect. Comparing baseline directly against disruption plus a new policy changes two causes and does not isolate either.</P><DocFigure id="controlled-comparison" /><P>The <DocLink to="your-first-project">control-unit tutorial</DocLink> follows this three-run design. Duplicate a scenario, change one factor, retain the original and give the new scenario a name describing its difference.</P></Section>
<Section id="the-four-conditions" title="What the comparison checks"><P>Open Simulation Lab → <strong>Compare</strong> and choose a baseline from scenarios with completed, non-exploratory results. Each other scenario is checked against that baseline separately; comparable scenarios become columns in the comparison matrix. Use the chips to include scenarios, rank by a KPI, and select a column to inspect its paired table. On a phone, use the ranked list. If every run is exploratory, first run a Validated Model through Policies → Run &amp; Validate. The comparison requires common random numbers enabled and matching seed specifications. It compares the run's policy-version ID, world fingerprint and disruption schedule, and requires exactly one of those components to differ. It rejects different engine versions when both are recorded.</P><P>Read a refusal literally: changing both policies and events requires a better controlled pair; two identical configurations have nothing to contrast. For older runs some comparison fields fall back to the scenario record. A passing screen check does not establish complete historical provenance.</P></Section>
<Section id="review-protocol" title="Check what the screen cannot decide for you"><Bullets items={[
<>Confirm dataset versions and the exact inputs behind each run. A changed price, BOM or capacity is a model change even when the label looks familiar.</>,
<>Use the same warm-up and measurement window for a policy-effect question. Confirm the event and enough recovery time are inside the window.</>,
<>Use completed replications with matched seeds. Read the actual paired count; the requested count can differ from the completed count.</>,
<>Review conversion notes on both runs. A new fallback or clamped setting may be another changed factor.</>,
<>Specify the practically important difference before choosing more replications. Do not keep sampling solely until a preferred result becomes significant.</>
]} /></Section>
<Section id="reading-the-table" title="Read the difference and its interval"><P>The comparison uses measures present on both sides. Paired differences compare matched replication results before summarizing their uncertainty. They can be more precise than subtracting two unrelated run means. Overlapping intervals on the two means do not by themselves decide the paired test.</P><P>Each scenario–KPI cell is a separate test. Looking across many cells increases the chance of a chance finding; select the primary outcome in advance and confirm a promising response with an independent experiment. The matrix does not directly test challengers against each other. A winner is meaningful only for a measure with a defined direction and a paired interval supporting that direction. Inventory and utilization are trade-offs, not quantities always improved by increasing or decreasing them. An unpaired or inconclusive result should be reported as such.</P><P>For a toy example, B serving five additional units every week may improve service, but if the response adds large holding cost the commercial decision can still be unattractive. Report service, loss, cost and the assumptions used to value them.</P></Section>
<Section id="scope" title="Application workflow versus engine library"><P>This guide describes the reachable baseline-versus-many view, whose tests remain pairwise. The repository also contains an experiment-designer component and engine-library stress/synergy functions; their presence alone does not make them application features. Use the documented application controls or the separately documented Python interfaces.</P><P>Next: <DocLink to="seeds-replications-confidence">seeds and precision</DocLink>, <DocLink to="kpis-and-resilience-index">KPI definitions</DocLink> and <DocLink to="verifiable-exports">exporting evidence</DocLink>.</P></Section>
</>; }
