import { PageTitle, Section, P, Key, Callout, Bullets, Steps, Defs, DocLink, AppLink, Term } from "@/components/docs/prose";
import { DocFigure } from "@/components/docs/DocFigure";
import { ExampleDownloads } from "@/components/docs/ExampleDownloads";

export default function Guide() { return <>
<PageTitle lead="Explore supplied company relationships and the evidence gaps around them.">Firm-Level Network</PageTitle>
<Section id="what-you-see" title="A separate company graph"><P>The firm view reads deep-tier nodes and edges. A node identifies a company; an edge records the supplied src_uid → dst_uid relationship. The layout draws connections without arrowheads, so use edge details and the source/destination identifiers when direction matters. Company depth and seed status drive tier classification.</P><DocFigure id="firm-network" /><P>Revenue and relative-revenue attributes are separate from physical material quantities. A displayed weight can include a fallback when revenue data is missing; inspect data coverage before interpreting it as money or purchasing share.</P></Section>
<Section id="worked-example" title="Why the tutorial may have no firm graph"><P>The control-unit files describe S-BOARD and S-CASE supplying materials to Assembly, and Assembly serving C-ASSEMBLY. They do not include deep-tier company-node and company-edge files. An empty firm graph after completing that tutorial does not mean its product network failed.</P><P>To extend it, collect and document company relationships with stable company identifiers and evidence, then upload the corresponding deep-tier files. A company name, directory listing or manufacturing capability alone is not proof that it supplies a named buyer. Keep possible suppliers separate from established relationships in your research data.</P></Section>
<Section id="questions" title="Questions this graph can support"><P>Look for recorded shared upstream dependencies, concentration in industries or locations, and companies with many supplied connections. A common upstream firm can suggest correlated exposure, but only within the observed network and evidence quality.</P><P>Low connectivity can reflect a genuinely sparse chain, incomplete data collection, unresolved company identities, missing endpoints or filtering. 'No shared supplier found' is not equivalent to 'the suppliers are independent'. Report coverage and missingness with any conclusion.</P></Section>
<Section id="upload" title="Review deep-tier files before importing"><P>Deep-tier uploads use bulk paths distinct from the staged CSV workflow for BOM and logistics. Do not assume a raw-file archive or a promotion diff. Keep the previous export, verify every edge endpoint has a node, and review <DocLink to="deep-tier-nodes">Deep-Tier Nodes</DocLink> and <DocLink to="deep-tier-edges">Deep-Tier Edges</DocLink> before uploading.</P><P>Check tier and direction conventions against the data source. Do not use BOM level as a company tier or fill unknown weights with invented transaction values.</P></Section>
<Section id="simulation" title="What this graph does not simulate"><P>The ordinary worker's frozen-input model reads operational supplier, material, product, BOM and demand tables. Deep-tier company edges do not automatically become capacity-constrained upstream production stages. A central firm in this graph is a research lead, not a measured simulation impact.</P><P>Next: <DocLink to="network-science-metrics">network measures</DocLink> for structural interpretation, or <DocLink to="product-level-network">the operational product graph</DocLink>.</P></Section>
</>; }
