import { PageTitle, Section, P, Key, Callout, Bullets, Steps, Defs, DocLink, AppLink, Term } from "@/components/docs/prose";
import { DocFigure } from "@/components/docs/DocFigure";
import { ExampleDownloads } from "@/components/docs/ExampleDownloads";

export default function Guide() { return <>
<PageTitle lead="A browser, a control plane and a simulation engine with separate responsibilities.">How SuReSuite is designed</PageTitle>
<Section id="the-journey" title="From a decision to evidence"><P>SuReSuite lets you prepare a supply-chain model, choose operating policies, run scenarios and compare outcomes. Its graphs help inspect relationships; its simulation estimates behavior under explicit assumptions. A visible relationship and a simulated mechanism are different things.</P><DocFigure id="tiers" /><DocFigure id="system-components" /></Section>
<Section id="components" title="Where work happens"><Defs items={[
{term:"React / Vite interface",def:"Project Manager uploads data; Policies edits and validates decisions; Simulation Lab manages scenarios, runs and comparisons. The manual is rendered from React components and generated reference data."},
{term:"Supabase control plane",def:"Stores accepted inputs, policy and dataset versions, validations and run records. Edge functions and database RPCs handle requests. Authorization must be traced at those boundaries; hiding a button is not enforcement."},
{term:"Python execution",def:"The Fly worker loads frozen input and policy snapshots, maps them into scsim and persists results. A shared local entry point also supports offline execution. The application additionally has a browser-engine path for validation."},
{term:"scsim engine",def:"A weekly simulation of suppliers, materials, a focal production stage and customers. Policy plugins implement supported decisions. Engine-library features are not all exposed through the application."}
]} /></Section>
<Section id="engineer" title="Start as a new engineer"><P>Read the repository's README and CLAUDE.md, install the lockfile dependencies with <Term>npm ci</Term>, and start Vite with <Term>npm run dev</Term>. This serves the frontend; it does not create a local Supabase database or a Fly worker.</P><P>The current Supabase client has project configuration in its source. Do not assume an arbitrary .env file redirects the application into an isolated backend. Use the offline example for local simulation checks, and arrange a dedicated backend before exercising writes from the full app.</P><P>Run <Term>python scripts/verify-manual-example.py</Term> for the local frozen-input example after installing the Python dependencies. For the manual, run <Term>npm test -- src/components/docs</Term>, <Term>npm run typecheck</Term>, <Term>npm run check:docs</Term> and <Term>npm run build</Term>.</P></Section>
<Section id="one-source" title="Where definitions come from"><P>The repository data-contract sidecars drive table references and ingestion metadata. The engine registry drives policy schemas and engine references. Generated sections can be checked against their generators; explanatory prose still needs review when behavior changes.</P><P>Do not hand-edit generated table pages or engine reference pages. Change their source metadata or generator and regenerate. Preserve the engineering plan as an engineering record; it is not the first reading task for a supply-chain analyst.</P></Section>
<Section id="limits" title="What this architecture does not establish"><P>A stored version does not prove model validity or deployment parity. Not all ingestion paths use staging, and historical records can have incomplete provenance. Current source review also identifies a browser simulation authorization gap; see <DocLink to="roles-and-capabilities">roles and capabilities</DocLink>. Do not treat the architecture diagram as a certification of access control.</P><P>Choose a path: <DocLink to="your-first-project">analyst tutorial</DocLink>, <DocLink to="reading-your-results">manager/researcher review</DocLink> or <DocLink to="getting-an-api-key">API access</DocLink>.</P></Section>
</>; }
