import { PageTitle, Section, P, Key, Callout, Bullets, Steps, Defs, DocLink, AppLink, Term } from "@/components/docs/prose";
import { DocFigure } from "@/components/docs/DocFigure";
import { ExampleDownloads } from "@/components/docs/ExampleDownloads";

export default function Guide() { return <>
<PageTitle lead="Understand a displayed value, save a decision, and check the value that reaches the engine.">How policies work</PageTitle>
<Section id="what-a-policy-is" title="What a policy changes"><P>Inputs describe demand, BOM, lanes and capacities. Policies decide replenishment, sourcing, production and treatment of unmet demand. The same input network can produce different outcomes under different policies, but only when the chosen field reaches the engine.</P><P>On <AppLink to="/policies">Policies</AppLink>, work through Supplier, Plant and Customer stages, then Run &amp; Validate. Read each value's source marker and field details. Unsaved drafts, saved row overrides, project defaults and uploaded values are different states.</P><DocFigure id="resolution-order" /></Section>
<Section id="precedence" title="There is no universal precedence ladder"><P>Resolve each field separately. For master-backed economics such as material cost, a saved policy override can replace the uploaded master value; without either, a lane-based derivation or explicit default may apply. Demand, lead time and finished-goods policy fields use different chains. The stage references show the field-specific chains and engine-read status.</P><Defs items={[
{term:"Material cost example",def:"M-BOARD costs 20 in the tutorial master. A policy override of 25 changes the simulated material valuation while leaving the uploaded master at 20. Removing the override restores the next applicable source; re-uploading the master does not remove the override."},
{term:"Missing versus zero",def:"A blank can mean no override, derive a value or use a default. Zero is not automatically missing. For example, zero opening material stock starts empty, while zero safety-stock days requests no fixed-days buffer. Check the field's bounds and engine chain before entering zero."},
{term:"Finished-goods target",def:"For MTS products, an explicit base-stock target S is the target; the FG safety buffer is not added again. When S is missing, a target can be derived. There is no new FG safety-buffer control; an applicable value saved by an older policy appears as a legacy notice with Remove. MTO products do not use FG-stock policy controls."},
{term:"Lead time",def:"The supplier-stage lead-time display comes from the inbound lane. Change the lane through the data workflow; a display in days does not change the engine's weekly time step."}
]} /></Section>
<Section id="replenishment" title="Read the parameters for the selected type"><P>A typed material reorder point s or target S is an absolute level; the engine does not add safety stock on top. Leave those levels empty to use the formula and its buffer. Periodic replenishment reads its review period T. An (R,Q) row requires a positive lot Q, either on the row or inherited from the project; it has no coverage κ control. MRP takes replenishment from the plan. If a stored parameter belongs to a previous type, the mapper drops it and records a warning.</P></Section>
<Section id="worked-response" title="Use the control-unit example"><P>At 100 products/week the BOM implies 100 boards and 200 housings/week. The tutorial starts with min-max replenishment and two weeks of coverage, zero days of material safety stock, and explicit opening quantities. To test a buffer, change only Safety stock to 28 days on the material rows, save a new policy version, and rerun the same supplier disruption.</P><P>Do not also change demand, opening inventory or the disruption schedule. Keep the baseline version so you can compare the two policies. The buffer can improve service while increasing inventory and holding cost; review both. The 28-day setting is illustrative.</P></Section>
<Section id="save" title="Draft, saved version and Validated Model"><P>A value visible in an edited cell may still be a draft. Save the edit and check that no unsaved indicator remains. A policy version captures a saved bundle for a run. A preset is a reusable starting configuration, not evidence that it suits your chain. A Validated Model binds policy and dataset versions to validation evidence and adopted simulation settings.</P><P>When the run control offers <strong>Save version and run</strong>, it is asking to bind the edits to a version. A prior validation can become outdated after inputs or policies change. Inspect the credibility message; do not assume an old validation covers a new scenario.</P></Section>
<Section id="what-reaches-the-engine" title="Stored does not mean simulated"><P>Use <DocLink to="supplier-stage">Supplier</DocLink>, <DocLink to="plant-stage">Plant</DocLink> and <DocLink to="customer-stage">Customer</DocLink> references for each field's engine status. Disabled milestone controls describe planned support. Transport-family settings and routing flags must not be assumed to be simulated simply because they can be stored or displayed.</P><P>The engine currently models a single focal production stage. Multi-level BOM display does not introduce subassembly capacity or work-in-progress. After every significant policy change, inspect the conversion notes and effective values. Version history → Export now maps the saved policy through the same engine-input path as a run. Its Read me sheet identifies whether it used the latest run’s dataset and scenario or current project data; review that provenance before treating it as evidence for a particular run.</P><P>Next: <DocLink to="policy-versions-and-presets">versions and presets</DocLink>, then <DocLink to="model-validation">model validation</DocLink>.</P></Section>
</>; }
