import { PageTitle, Section, P, Key, Callout, Bullets, Steps, Defs, DocLink, AppLink, Term } from "@/components/docs/prose";
import { DocFigure } from "@/components/docs/DocFigure";
import { ExampleDownloads } from "@/components/docs/ExampleDownloads";

export default function Guide() { return <>
<PageTitle lead="Follow the tutorial\u2019s BOM line through upload, review, accepted inputs and a frozen run.">How your data flows</PageTitle>
<Section id="the-shape" title="One row, several states"><P>The tutorial line P-CONTROL → M-CASE with consumption 2 begins as a CSV row. It becomes an accepted input only after review and promotion. Derived graphs and simulation results are separate products of those inputs.</P><DocFigure id="flow" /></Section>
<Section id="upload" title="Raw file and staged rows"><P>For contract-driven CSV datasets, landing records the uploaded file and stages original cells beside parsed values and findings. These rows can be inspected before they change the canonical model. An error on consumption rate can hold the BOM row while other valid rows remain eligible.</P><P>File findings use error, warn and info; the simulation-readiness gate uses block, warn and info. Passing a CSV parser does not prove that every referenced identifier exists or that the assembled model is suitable for simulation.</P></Section>
<Section id="promote" title="Accepted inputs"><P>Promotion applies eligible rows using the dataset's natural key. In the example, the product/material pair identifies the BOM line. Uploading that pair with consumption 3 proposes a changed value, not another independent requirement. Inspect the diff before promotion; the promotion recomputes the changes against current inputs.</P><P>Rates and durations on supported columns normalize at promotion. Some downstream readers retain conversions for older data, so the rule is not 'nothing converts later'. Keep units explicit and inspect the stored canonical value.</P></Section>
<Section id="compute" title="Derived data and graphs"><P>Derived lanes, summaries and network measurements answer different questions. They may need refresh or recomputation after an input change. Read freshness and provenance where provided; do not assume every historical derived row records the inputs that produced it.</P><P>Node-list and deep-tier uploads use separate bulk paths. They do not share all the staging and raw-file behavior above. A firm edge is data supplied to the graph, not a relationship proved by drawing it.</P></Section>
<Section id="freeze" title="Frozen inputs, policies and results"><P>A dataset version stores a snapshot of the relevant model data. A policy version stores decisions. Dispatch binds a run to those versions, the scenario specification and engine information. The current worker consumes the frozen dataset and policy snapshots through its shared local execution path.</P><P>Validation adds evidence and adopted protocol settings; it is not a guarantee that a forecast is correct. After changing accepted inputs, inspect which version a new run uses and whether the validation is stale. An earlier run remains evidence about its earlier inputs.</P><P>For handover, retain the dataset and policy exports, scenario, seeds, engine build, conversion notes and completed replication count. A hash helps identify an artifact but does not itself supply missing historical data or prove the deployment ran that build.</P><P>Next: <DocLink to="dataset-versions">dataset versions</DocLink>, <DocLink to="policy-versions-and-presets">policy versions</DocLink> and <DocLink to="verifiable-exports">exports</DocLink>.</P></Section>
</>; }
