import { PageTitle, Section, P, Key, Callout, Bullets, Steps, Defs, DocLink, AppLink, Term } from "@/components/docs/prose";
import { DocFigure } from "@/components/docs/DocFigure";
import { ExampleDownloads } from "@/components/docs/ExampleDownloads";

export default function Guide() { return <>
<PageTitle lead="Use these boundaries when deciding what a result can support.">Known limits</PageTitle>
<span id="data-limits" />
<span id="documentation-limits" />
<span id="how-to-use" />
<span id="model-limits" />
<span id="why-at-the-front" />
<Section id="model" title="Model fidelity"><P>The current engine uses weekly steps and fluid quantities, with suppliers, materials, one focal production stage and customers. Multi-level BOMs are flattened into root-to-leaf requirements for simulation. Intermediate stock, work-in-progress and independent subassembly capacities are not represented just because the process graph displays them.</P><P>Company relationships in the deep-tier graph do not automatically become simulated upstream dependencies. Network centrality indicates structure within the supplied graph; it is not a measured loss or a causal disruption ranking.</P><DocFigure id="trust-boundaries" /></Section>
<Section id="data" title="Data and mapping"><P>Contract-driven CSV uploads have staging and natural-key promotion. Node-list and deep-tier bulk uploads are exceptions. Missing optional values can invoke defaults, and generated/derived values can differ from original cells. Inspect promotion diffs and run conversion notes.</P><P>Changing accepted data can make analyses and validation stale. Current frozen-input execution improves run provenance, but older runs and derived records may not carry complete versions. A generated reference also requires regeneration and review when its source changes.</P></Section>
<Section id="policies" title="Policy support and results"><P>Some controls are stored or reserved without affecting the current engine. Use the per-field stage reference and engine status rather than inferring support from a field's presence. Finished-goods controls apply to MTS products; MTO does not hold FG stock through that policy.</P><P>The Resilience Index belongs to the engine stress-battery library and is not emitted by ordinary application runs. Unavailable fill rate, recovery time or a series is not zero. Read measurement-window and censoring information before reporting a conclusion.</P></Section>
<Section id="security" title="Access-control and deployment limits"><P>Source review identified incomplete caller authorization on the browser simulation endpoint. <DocLink to="roles-and-capabilities">Roles and capabilities</DocLink> distinguishes this from the scoped public API gateway. The documentation changes do not fix this issue, and no production bypass test was run.</P><P>The reviewed source and a live deployment can differ. The tutorial's CSV validation and engine execution are local; hosted upload promotion and browser-to-worker execution remain unverified for the sample.</P></Section>
<Section id="decision" title="What to report with a decision"><P>State the model boundary, data coverage, important assumed values, completed replication count, measured window and changed experimental factor. A confidence interval measures Monte Carlo precision conditional on these assumptions; it does not certify real-world validity.</P><P>When a limitation can reverse the decision, collect the missing evidence or test alternative assumptions before recommending action. See <DocLink to="reading-your-results">Reading your results</DocLink> and <DocLink to="experiments-and-comparison">Experiments &amp; comparison</DocLink>.</P></Section>
</>; }
