import { PageTitle, Section, P, Key, Callout, Bullets, Steps, Defs, DocLink, AppLink, Term } from "@/components/docs/prose";
import { DocFigure } from "@/components/docs/DocFigure";
import { ExampleDownloads } from "@/components/docs/ExampleDownloads";

export default function Guide() { return <>
<PageTitle lead="Inspect BOM dependencies and distinguish component depth from actual production operations.">Process-Level Network</PageTitle>
<Section id="what-you-see" title="What a process node means here"><P>This view expands component relationships using the multi-level BOM when available. It displays suppliers, materials and subassemblies, finished products and customers. It is a BOM-oriented view, not a routing model of individual machines, processing steps or labor stations.</P><DocFigure id="process-network" /><P>Role and depth colors help distinguish levels; line width uses the computed flow scale. Read selected-node and edge details for quantities. Screen position and size are not evidence of process duration or capacity.</P></Section>
<Section id="worked-example" title="The same control unit at two depths"><P>The tutorial uses a single-level BOM: one board and two housings feed P-CONTROL. Its process view therefore adds little depth beyond the product view. This is expected; a deeper-looking drawing would require additional BOM data.</P><P>As a separate illustration, suppose a board assembly needs two chips and the product needs one board assembly. A multi-level BOM can show chip → board assembly → product. Two chips per assembly times one assembly per product implies two chips per product. This illustration is not included in the executable single-level sample.</P></Section>
<Section id="tiers" title="BOM level is not company tier"><P>BOM depth counts component relationships. Company tier counts organizational relationships relative to a focal firm. A board supplier may be a tier-one company even when its board is several BOM levels below a finished product. Do not transfer one kind of depth onto the other.</P></Section>
<Section id="focus" title="Follow a dependency without losing context"><P>Search for a component, focus its upstream and downstream path, and restore <strong>Show all</strong> before assessing overall connectivity. The top-flow filter is useful for readability, but a low-volume component can still stop every product that needs it.</P><P>If a component is isolated, inspect higher-level component identifiers, product roots, consumption rates and the selected BOM configuration. Check filters and derived-data freshness before editing source data. Do not add a speculative edge just to make the picture connected.</P></Section>
<Section id="disruption" title="From graph inspection to a scenario"><P><strong>Add disruption event</strong> can create or update a scenario from a supported target. Supplier and plant targets are supported by the engine path; a material or subassembly needs an appropriate supplier target where offered. Confirm the resolved target in the scenario and conversion notes.</P><Callout title="Displayed depth is not simulated production depth"><p>The worker currently flattens multi-level BOMs to root-to-leaf requirements for the single-stage engine. Intermediate inventory, work-in-progress, lead time and capacity are not independently simulated. Use this view for structural inspection; do not report a subassembly bottleneck experiment as verified without a model that represents it.</p></Callout><P>Next: <DocLink to="firm-level-network">company relationships</DocLink> and <DocLink to="disruptions">disruption configuration</DocLink>.</P></Section>
</>; }
