import { PageTitle, Section, P, Key, Callout, Bullets, Steps, Defs, DocLink, AppLink, Term } from "@/components/docs/prose";
import { DocFigure } from "@/components/docs/DocFigure";
import { ExampleDownloads } from "@/components/docs/ExampleDownloads";

export default function Guide() { return <>
<PageTitle lead="Inspect which suppliers and materials each finished product depends on.">Product-Level Network</PageTitle>
<Section id="what-you-see" title="Read the four roles"><P>The product view groups suppliers, purchased materials, finished products and customers. Edges follow the supplied lane and BOM relationships through these roles. Echelon colors identify roles; they are not risk ratings. Edge width reflects the view's computed flow scale, not an independently measured shipment.</P><DocFigure id="product-network" /><P>Layout and node size support legibility. Read the legend, selected-node details and numerical metric before interpreting visual prominence as economic importance.</P></Section>
<Section id="worked-example" title="Find P-CONTROL in the tutorial"><P>Use the <DocLink to="your-first-project">control-unit example</DocLink>. Search for P-CONTROL and follow M-BOARD and M-CASE back to S-BOARD and S-CASE, and forward to C-ASSEMBLY. The BOM requires one board and two housings per product. At demand of 100/week that implies 100 boards and 200 housings/week.</P><P>These are BOM-implied requirements. Inbound volumes describe supplied rates and help determine sourcing shares; they are not proof of actual transactions or a second independent measure of demand. Avoid summing edges across different material units as if they were all the same commodity.</P></Section>
<Section id="questions" title="What this view can answer"><P>Use it to identify products sharing a purchased material, materials with only one recorded supplier and the customer demand connected to a product. Focus a node to inspect its supply path; restore the full view before concluding that a missing connection does not exist.</P><P>A second supplier only represents an available alternative if the underlying data and operating assumptions support it. Two supplier nodes also do not prove independent upstream sources.</P></Section>
<Section id="missing" title="When an edge is missing"><P>Check selected project, active filters, identifier spelling, promotion status and whether derived data needs refreshing. A master row does not create a lane or BOM line. A disconnected material may be deliberately unused, incorrectly identified or awaiting relationship data.</P><P>For multi-level data the product view collapses internal BOM structure into purchased-material to finished-product dependencies. Use the <DocLink to="process-level-network">process view</DocLink> to inspect intermediate components.</P></Section>
<Section id="simulation" title="What reaches simulation"><P>The engine maps accepted BOM, supplier/material lanes and customer/product demand into its model. The graph's screen layout, node size and computed centrality are not simulation parameters. The current engine has one focal production stage; displaying a multi-level BOM does not create intermediate stock, capacity or processing time.</P><P>Next: inspect <DocLink to="process-level-network">BOM depth</DocLink>, then <DocLink to="how-policies-work">set operating policies</DocLink>. Read conversion notes after the run to confirm the input mapping.</P></Section>
</>; }
