import { PageTitle, Section, P, Key, Callout, Bullets, Steps, Defs, DocLink, AppLink, Term } from "@/components/docs/prose";
import { DocFigure } from "@/components/docs/DocFigure";
import { ExampleDownloads } from "@/components/docs/ExampleDownloads";

export default function Guide() { return <>
<PageTitle lead="Find who can work on a project and request the right level of access.">Project access</PageTitle>
<span id="members" />
<span id="related" />
<span id="why-separate" />
<Section id="roles" title="Start with the project, not the account label"><P>A project has an owner and can have members with viewer, analyst or editor rights. Project roles are separate from account roles and organization membership. The current project-rights defaults are documented in <DocLink to="roles-and-capabilities">Roles and capabilities</DocLink>; notably, an analyst can run simulations but does not receive input editing, policy editing or export by default.</P><DocFigure id="project-access-review" /></Section>
<Section id="check" title="Inspect effective access"><P>Use your profile's project-access information to see the effective role and rights for the selected project. Administrators can use the project-access administration screen to inspect ownership, membership and delegation. Access to that administration screen is itself restricted.</P><P>Ask for a right tied to a concrete task: 'edit input data for Control-unit tutorial' is clearer than 'make me an admin'. An editor can prepare inputs and policies without becoming the project's owner. Ownership and project-setting changes have separate checks.</P></Section>
<Section id="delegation" title="Delegation and expiration"><P>Delegation can grant temporary project access under the application's delegation rules. Check both the effective role and expiry; a previous successful session is not proof that the grant remains valid. When a grant expires, ask the owner or administrator to review the task rather than assuming the project was deleted.</P></Section>
<Section id="errors" title="When access and controls disagree"><P>Record the project, action, effective-right display and exact backend error. Reloading can resolve a stale interface state, but cannot correct a missing permission. The absence of a button and a denied server request are different evidence.</P><Callout title="Enforcement has known gaps"><p>The current source does not establish uniform enforcement across every browser and backend path. The browser simulation dispatch gap is described in <DocLink to="roles-and-capabilities">Roles and capabilities</DocLink>. This documentation records it; it does not change access control or certify a live deployment.</p></Callout><P>Documentation release access is separate. Being unable to open a manual section is not itself evidence that your project role changed.</P></Section>
</>; }
