import { REPLICATION_SERIES_FACTS as SERIES } from "@/components/docs/generated/policy.generated";
import { PageTitle, Section, P, Key, Callout, Bullets, Steps, Defs, DocLink, AppLink, Term } from "@/components/docs/prose";
import { DocFigure } from "@/components/docs/DocFigure";
import { ExampleDownloads } from "@/components/docs/ExampleDownloads";

export default function Guide() { return <>
<PageTitle lead="Check the run, inspect assumptions, and then interpret service, cost and uncertainty.">Reading your results</PageTitle>
<Section id="the-order" title="Start with the run record"><P>Open the completed run in <AppLink to="/simulation-lab">Simulation Lab</AppLink> → <strong>Results</strong>, or the shared results panel in Policies → Run &amp; Validate. Confirm status, completed replication count and the exact dataset, policy and scenario versions. A preliminary estimate can change as replications finish. A failed or cancelled run with some rows is not equivalent to the requested completed experiment.</P><P>Read the credibility badge and <strong>Engine conversion notes</strong> before quoting a KPI. Notes can describe defaults, clamping, unsupported values or a target that could not be used. Record any consequence for your business question. A clean run is still only a model of its supplied assumptions.</P><DocFigure id="kpi-vocabulary-gap" /></Section>
<Section id="the-panels" title="Use each panel for a question"><Defs items={[
{term:"KPI summary across replications",def:"Read the mean, confidence interval, standard deviation, range and count. Rows are driven by measures actually returned by the engine; labels and improvement directions come from the KPI catalog. An unavailable measure must not be interpreted as zero."},
{term:"Convergence plot",def:"Follow the running estimate and interval for the selected objective. A stable estimate helps assess Monte Carlo precision; it does not validate demand, capacity or the BOM. One replication cannot establish a between-replication interval."},
{term:"Replication & seed explorer",def:"Inspect the weekly trace and individual replications. Identify when the shock starts, whether stock delays its effect, and whether service recovers inside the measured window."},
{term:"Inventory and capacity",def:"Read materials and finished goods separately. Average inventory is a level averaged over the analysis window, not a sum of weekly inventory. Capacity utilization alone does not show whether capacity refused production; inspect binding measures too."},
{term:"Per-item inspection",def:"Use an inspection run when you need product/material detail. Availability depends on what that run recorded; an absent series is not evidence of zero inventory or zero demand."}
]} /></Section>
{SERIES.heatmapRemoved ? <Callout title="Utilization heatmap — removed"><p>The former panel depended on a per-node <Key>capacity_utilization</Key> series that the engine did not produce. Its removal does not mean capacity is unlimited. Use the returned aggregate capacity measures and binding indicators described above.</p></Callout> : null}
<Section id="worked-reading" title="Interpret the control-unit experiment"><P>The tutorial's two material requirements are 100 boards and 200 housings/week. During an 80% capacity reduction, S-BOARD's declared 150/week capacity falls to 30/week. Opening stock and replenishment policies can delay customer impact, so do not expect the service drop to start at the same instant as the capacity event.</P><P>Compare baseline against disruption to measure the shock, then compare the same disruption under two policy versions to measure the buffer's effect. Read lost sales, service and cost together. Cost of resilience includes its engine-defined components, including lost-sales cost; it is not simply cash spent purchasing extra stock. Avoid subtracting the same loss twice in a benefit calculation.</P><P>The example uses deterministic demand and lead time. Identical replications and a zero-width interval are expected here; they do not demonstrate certainty about a real business.</P></Section>
<Section id="window" title="Know the denominator and time window"><P>Fill rate is fulfilled demand value divided by demand value in the engine's analysis window. It is value-weighted, so expensive products contribute more. No demand means no measurable fill rate. A missing recovery metric can mean recovery was not observed within the available window, not instantaneous recovery.</P><P>The engine separates total horizon, excluded warm-up and the measurement window. Read the run-window summary and conversion notes. Extending the horizon does not necessarily extend the measured period by the same amount. Check whether the disruption and recovery fall inside that period before comparing.</P></Section>
<Section id="trust" title="What a result can support"><P>A narrow interval estimates Monte Carlo precision conditional on the model. It does not address missing suppliers, incorrect BOM quantities, uncertain demand forecasts or policy mapping errors. For a managerial conclusion, record those assumptions, test plausible alternatives and state where the conclusion changes.</P><Callout title="Resilience Index availability"><p>The engine's stress-battery library defines a Resilience Index. Ordinary application runs do not emit it. Do not infer a score from an empty field or describe a normal run as producing one. <DocLink to="kpis-and-resilience-index">The KPI reference</DocLink> explains the formula and normalization.</p></Callout><P>Next: <DocLink to="experiments-and-comparison">controlled comparisons</DocLink> and <DocLink to="verifiable-exports">verifiable exports</DocLink>. Preserve the inputs and protocol with the result, not just a screenshot of a mean.</P></Section>
</>; }
