import { ACCOUNT_ROLES, ACCOUNT_ROLE_GLOSS, ACCOUNT_ROLE_LABELS } from "@/lib/auth/roleGloss";
import { FROZEN_CELL } from "@/components/shared/frozenCell";
import { PageTitle, Section, P, Key, Callout, Bullets, Steps, Defs, DocLink, AppLink, Term } from "@/components/docs/prose";
import { DocFigure } from "@/components/docs/DocFigure";
import { ExampleDownloads } from "@/components/docs/ExampleDownloads";

export default function Guide() { return <>
<PageTitle lead="Understand your project rights and distinguish interface controls from server enforcement.">Roles and capabilities</PageTitle>
<Section id="layers" title="Three different kinds of role"><P>An account role controls application-level capabilities. Organization membership places a user in an organizational context. A project role controls the rights shown for one project. Being a project owner is not the same as being an organization administrator, and a role on one project does not describe another project. Two rights cross the layers: an Admin or Owner of an organization may create projects in it, and may delete its projects and the data inside them, whatever the account role. Both apply to the organization you are working in, so switch to that organization on your profile first.</P><DocFigure id="capability-layers" /></Section>
<Section id="account-roles" title="Account-role defaults"><P>These are the same descriptions shown by account administration. Project rights and explicit grants still need a separate check.</P><Defs items={ACCOUNT_ROLES.map(role => ({ term: ACCOUNT_ROLE_LABELS[role], def: ACCOUNT_ROLE_GLOSS[role] }))} /></Section>
<Section id="project-rights" title="Default project rights in the current source"><P>The current migration-defined project roles are viewer, analyst, editor and owner. Their defaults for the four project controls are:</P><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className={FROZEN_CELL}>Role</th><th>Edit inputs</th><th>Edit policies</th><th>Run simulations</th><th>Export</th></tr></thead><tbody>{[
['Viewer','No','No','No','No'],['Analyst','No','No','Yes','No'],['Editor','Yes','Yes','Yes','Yes'],['Owner','Yes','Yes','Yes','Yes']
].map(row => <tr key={row[0]}>{row.map((v,i) => <td className={`${i === 0 ? FROZEN_CELL : ""} border-b border-border px-2 py-3`} key={i}>{v}</td>)}</tr>)}</tbody></table></div><P>This is the source-defined default matrix, not a live audit of your account. Account activity, project access, administrative overrides and delegation can affect the effective answer. Project settings and membership administration have separate checks; an editor's four rights do not imply ownership.</P></Section>
<Section id="find-rights" title="Check and resolve an access problem"><P>Open your profile's project-access information and check the effective role and reason for the right in question. Confirm the selected project. If you can view data but cannot edit policies, an analyst or viewer role may explain it. Ask the owner or an administrator for the required right; changing a policy parameter will not clear a permission failure.</P><P>For upload failures, distinguish landing from promotion. The interface and backend check different stages. Record the action, project and exact error so the administrator can identify the failing boundary. Do not treat a hidden control as evidence that direct requests are impossible.</P></Section>
<Section id="enforcement" title="What is verified and what remains a gap"><P>Some operations, including staged promotion, have database role checks. The public API gateway authenticates keys, checks scopes and project tenancy, and fails closed on authorization errors. These checks do not establish that every browser RPC and edge function enforces the same model.</P><Callout tone="limit" title="Known browser simulation authorization gap"><p>Source review found that the browser simulation endpoint accepts an Authorization header, can continue without an authenticated Supabase user, and checks project existence with service privileges. Its dispatch helper assumes the caller already authorized the request. This path does not establish the caller's project role before dispatch. Interface restrictions therefore must not be described as a complete security boundary. No production bypass test or permission change was performed during this documentation review.</p></Callout><P>Deployment parity remains unverified. The separate engineering review records affected paths and follow-up work. Use <DocLink to="getting-an-api-key">the scoped public API</DocLink> for documented integrations; do not build integrations against internal browser RPCs.</P></Section>
<Section id="next" title="Related access questions"><P><DocLink to="project-access">Project access</DocLink> explains project administration. <DocLink to="organizations-and-members">Organizations and members</DocLink> covers organization context. Documentation sections have their own release rules: being able to read a page does not confer access to the corresponding project action.</P></Section>
</>; }
