import { PageTitle, Section, P, Key, Callout, Bullets, Steps, Defs, DocLink, AppLink, Term } from "@/components/docs/prose";
import { DocFigure } from "@/components/docs/DocFigure";
import { ExampleDownloads } from "@/components/docs/ExampleDownloads";

export default function Guide() { return <>
<PageTitle lead="Separate random-run precision, startup effects and uncertainty about the real supply chain.">Seeds, replications &amp; confidence</PageTitle>
<Section id="seeds" title="Seeds and common random numbers"><P>A seed identifies a random stream within a particular implementation. Keep the engine build, inputs and protocol as well as the seed; the seed alone is not a promise of identical output across every version and environment.</P><P>Common random numbers help compare alternatives under coordinated demand and supply draws. Keep the same seed specification in both scenarios. The comparison panel checks this before presenting a paired result.</P><DocFigure id="replications" /></Section>
<Section id="replications" title="How many replications?"><P>A replication is one simulated realization. Replications measure variation caused by the model's random inputs. More replications can improve precision, with additional compute cost, but there is no universally sufficient count.</P><P>Use the convergence view and adopted validation settings. Decide what difference matters for your decision, then ask whether the interval is narrow enough to distinguish it. For a deterministic teaching model, three identical replications exercise the workflow but add no empirical evidence about real-world variability.</P></Section>
<Section id="warmup" title="Warm-up and the measurement window"><P>Opening inventory and an initially empty pipeline can influence early weeks. Excluding warm-up can help study ongoing operations. If the question is specifically about startup or recovery from an empty system, excluding it can remove the phenomenon you wanted to study.</P><P>The application supports adopted validation settings and manual warm-up. Keep the same adopted window across controlled variants unless window length is the experimental factor. Inspect the actual engine window: it is distinct from the full horizon and can be limited or shortened.</P></Section>
<Section id="confidence" title="What the interval means"><P>A confidence interval describes uncertainty in an estimated model quantity from finite replications. The min/max range instead describes observed extremes in those replications. Neither is a complete prediction interval for every possible future business outcome.</P><Callout title="Precision is not validity"><p>A narrow interval can coexist with a wrong demand mean, missing common supplier, incorrect BOM or unrealistic capacity. Review inputs and conversion notes, compare against observations where available, and test plausible alternative assumptions. A zero-width interval in the deterministic tutorial reflects its assumptions.</p></Callout><P>If time to recover is censored because recovery was not seen before the window ended, report that limit; do not replace it with zero. If no demand exists in the measured window, fill rate is unavailable.</P><P>Next: <DocLink to="model-validation">model validation</DocLink> and <DocLink to="experiments-and-comparison">controlled comparison</DocLink>.</P></Section>
</>; }
