import { PageTitle, Section, P, Key, Callout, Bullets, Steps, Defs, DocLink, AppLink, Term } from "@/components/docs/prose";
import { DocFigure } from "@/components/docs/DocFigure";
import { ExampleDownloads } from "@/components/docs/ExampleDownloads";

export default function Guide() { return <>
<PageTitle lead="Run a controlled scenario from a saved model, then inspect completion and compare.">Simulation Lab — running an experiment</PageTitle>
<Section id="the-rail" title="Before you run"><P>Start with a completed baseline from Policies → <strong>Run &amp; Validate</strong> and a saved Validated Model. In <AppLink to="/simulation-lab">Simulation Lab</AppLink>, the pinned baseline is inspected and copied; its validation is managed on Policies. Copying a scenario copies settings, not completed runs.</P><P>Select the intended project and scenario. Check your permission to run simulations. A scenario identifies horizon, warm-up, replication settings, seed, objective, disruption schedule and recovery configuration; the dispatched run binds these to saved input and policy versions.</P><DocFigure id="run-sequence" /></Section>
<Section id="setup" title="Setup and Recovery playbook"><P>In <strong>Setup</strong>, inspect the horizon, seed, common random numbers and replication count. Choose an objective the run actually reports, such as fill rate. The horizon is not the same as the engine's analysis window; use the window summary and conversion notes.</P><P>In <strong>Recovery playbook</strong>, set a supported event and any intended response. For the <DocLink to="your-first-project">control-unit tutorial</DocLink>, target S-BOARD with an 80% capacity reduction starting at week 16 for 4 weeks. Leave recovery levers off for the first disrupted run.</P><P>An empty disruption schedule is appropriate for a baseline. A stage's completion marker is a workflow hint, not proof of a correct experiment. Supplier and plant targets must resolve to entities the engine supports; a material shown in a graph is not automatically a supported direct disruption target.</P></Section>
<Section id="the-gate" title="Run: findings and save state"><P>In <strong>Run</strong>, clear every blocking finding. Read warnings before ticking the acknowledgement to run with defaults. A warning can describe a meaningful substitution, and accepting it records your choice; it does not make the input accurate.</P><P>Inspect the saved policy version. If edits are pending, use <strong>Save version and run</strong> where offered; if no version exists, save one first. A <strong>not permitted</strong> state needs the project owner's help, not a different numerical setting.</P><Key>Checkpoint: the submitted run has an ID, version bindings and a visible status. Clicking Run alone is not completion.</Key></Section>
<Section id="how-a-run-goes" title="Queued, running, done, failed or cancelled"><P>A queued run is waiting for execution. A running run can show preliminary results as replications arrive. Wait for done and confirm the completed count before using the full experiment. Closing the browser does not cancel a remote worker job.</P><P>Use the run's Cancel control to request cancellation and verify its final status. For a failure, retain the run ID and error, inspect conversion notes and input findings, then correct the cause before retrying. Do not repeatedly dispatch the same blocked model. Add replications only when the run controls support it and the existing model/protocol is still the one you intend.</P><P>Reuse can return an existing compatible completed result. Check its run record and bindings rather than treating a fast response as evidence that new computation occurred.</P></Section>
<Section id="results" title="Results and Compare"><P>Open <strong>Results</strong> to review completion, conversion notes, KPI distributions and weekly traces. Then open <strong>Compare</strong> and select a completed, non-exploratory baseline. Comparable scenarios appear together; select one to inspect its paired comparison. Preserve common random numbers and the seed, and change exactly one comparison component: policy, world or disruption schedule.</P><P>For baseline versus Board disruption, hold data and policies fixed. For a buffer response, keep the same disruption and vary only the policy version. The comparison checks several identities but does not replace your review of dataset versions, warm-up, measurement windows and assumptions.</P><P>Next: <DocLink to="reading-your-results">reading results</DocLink> and <DocLink to="experiments-and-comparison">comparison design</DocLink>.</P></Section>
</>; }
