import { PageTitle, Section, P, Key, Callout, Bullets, Steps, Defs, DocLink, AppLink, Term } from "@/components/docs/prose";
import { DocFigure } from "@/components/docs/DocFigure";
import { ExampleDownloads } from "@/components/docs/ExampleDownloads";

export default function Guide() { return <>
<PageTitle lead="Choose the correct dataset, review staged changes, and confirm which rows became model inputs.">Uploading data</PageTitle>
<Section id="where" title="Before uploading"><P>In <AppLink to="/project-manager">Project Manager</AppLink>, select the intended project and open <strong>Upload Data</strong>. Download the template from that dataset tab. Use CSV, one dataset per file; renaming an XLSX file does not convert it. The deep-tier network also has a JSON path with different handling.</P><P>For the tutorial, use <DocLink to="your-first-project">the control-unit files</DocLink>. A useful operating model needs BOM and inbound/outbound relationships plus economics, demand and capacity. Table presence alone does not establish run readiness.</P><DocFigure id="upload-review" /></Section>
<Section id="dependencies" title="Which file supplies which relationship"><Defs items={[
{term:"Masters",def:"Suppliers, Materials, Products and Customers describe the entities. Their identifiers must match the lane and BOM files exactly after trimming. A supplier master alone creates no supply relationship."},
{term:"BOM",def:"For the single-level tutorial, product_id + material_id connects P-CONTROL to M-BOARD at consumption_rate 1 and M-CASE at 2. These are material units per product unit, not percentages."},
{term:"Inbound logistics",def:"supplier_id + material_id identifies the supplying lane. volume is a rate in time_unit; lead_time has its own lead_time_unit. Use explicit week values in the example."},
{term:"Outbound logistics",def:"customer_id + product_id connects demand to a product. volume and time_unit define the demand rate; unit_price is the lane's selling price. Product-level and customer/product overrides may affect the effective demand used."},
{term:"Optional context",def:"Node locations support maps. Deep-tier nodes and edges support firm exploration. Multi-level BOM is for projects configured for that shape. None of these proves an upstream commercial relationship or a multi-stage simulation."}
]} /></Section>
<Section id="what-is-checked" title="Read findings before promotion"><P>The parser checks the file, then the contract checks headers and cells. Required headers and required values are different checks. Numeric cells use a decimal point; currency signs and thousands separators are not stripped. Blank optional cells supply no parsed value and may trigger a default. Zero is a supplied value and is accepted only where the field's rule allows it.</P><P>For example, BOM consumption must be greater than zero; zero customer priority is allowed and means lowest priority. A header not in the contract is not a way to introduce a new simulated parameter. Read its finding and use the dataset reference for accepted columns.</P><P>The review shows <strong>new</strong>, <strong>changed</strong>, <strong>unchanged</strong>, <strong>superseded</strong> and <strong>held</strong> rows. Open row details to see original and parsed values and findings. If the diff is unavailable, the rows are not yet compared; do not interpret them as all new. Recompute the comparison before deciding.</P><P>Choose <strong>Promote N rows</strong> when the intended changes are correct. Rows with errors remain held. Correct the original CSV and upload it again; verify accepted row counts afterward. This is a partial-success workflow, so check held rows even if promotion succeeds.</P></Section>
<Section id="uploading-twice" title="What re-uploading changes"><P>The staged BOM, lane, master, forecast and tier-supplier datasets are promoted with natural-key upserts. Matching identifiers update the matching row; new identifiers insert rows. Re-uploading does not mean replacing the entire table. Rows omitted from the new file are not a deletion instruction.</P><Defs items={[
{term:"Single-level BOM",def:"Within the project, product_id + material_id identifies the line."},
{term:"Inbound / outbound",def:"Within the project, supplier_id + material_id or customer_id + product_id identifies the lane."},
{term:"Item masters",def:"Within the project, the material, product, supplier or customer identifier identifies the entity."},
{term:"Multi-level and forecast files",def:"Use the dataset reference for the full key, including hierarchy or period fields; these are not interchangeable with single-level BOM or static demand."},
{term:"Node list / deep-tier network",def:"These use separate bulk upload paths. Do not assume staged review, raw-file retention or identical replacement behavior. Export a copy and check the relevant network-table guide before replacing data."}
]} /><P>Blank optional cells are not a reliable 'keep existing value' instruction. Promotion uses a column set for the run; a column supplied elsewhere in the file can also affect rows where it is blank. Review the actual changed values. If you meant to keep a value, include it explicitly.</P></Section>
<Section id="what-happens-after" title="Confirm success and recover safely"><P>After promotion, inspect the accepted table, refresh derived data if prompted, and run <DocLink to="verify-your-inputs">input verification</DocLink>. Check relationships as well as counts: two rows with the wrong IDs still describe the wrong model. Revalidate policies after a data change; old results refer to earlier inputs.</P><P>A missing Promote control can be a project-rights issue. An upload error, row validation failure and permission denial need different fixes; capture the exact message and project name for the owner rather than repeatedly uploading. Do not delete the project to repair a single malformed file.</P><P>Next: <DocLink to="how-your-data-flows">follow a file through the data lifecycle</DocLink> or inspect <DocLink to="data-model">dataset-specific field references</DocLink>.</P></Section>
</>; }
