// GENERATED by scripts/data-contract/gen-capabilities.mjs — DO NOT EDIT.
//
// The capability catalog, read out of the migrations that seed
// `public.capabilities`. Edit the migration, then run
// `npm run contract:capabilities`. `contract:check` fails when this file and
// the migrations disagree (PLAN.md §4 D33).
//
// 33 capabilities: 12 page, 21 feature.

export type CapabilityKind = 'page' | 'feature';

export interface CapabilityMeta {
  key: string;
  kind: CapabilityKind;
  label: string;
  description?: string;
  sortOrder: number;
}

/** Every feature key the database knows. A key absent here can never be granted. */
export type FeatureKey =
  | 'ai_chat'
  | 'simulation_lab'
  | 'project_intelligence'
  | 'data_editing'
  | 'data_edit_inputs'
  | 'data_edit_policies'
  | 'export'
  | 'agent_proposals'
  | 'agent_apply'
  | 'agent_data_steward'
  | 'agent_policy_configurator'
  | 'agent_vv_analyst'
  | 'agent_experiment_designer'
  | 'agent_explainer'
  | 'chat_history_sync'
  | 'reports'
  | 'agent_report_builder'
  | 'project_memory'
  | 'agent_cost_estimator'
  | 'agent_network_cartographer'
  | 'agent_disruption_sentinel';

export const PAGE_CAPABILITIES: CapabilityMeta[] = [
  { key: '/', kind: 'page', label: 'Getting Started', description: 'Landing / getting-started page', sortOrder: 10 },  // 20260711000002_unified_access_control.sql
  { key: '/project-manager', kind: 'page', label: 'Project Manager', description: 'Create, import and manage project datasets', sortOrder: 20 },  // 20260711000002_unified_access_control.sql
  { key: '/network/product-level', kind: 'page', label: 'Product-Level Network', description: 'Product-level network view', sortOrder: 30 },  // 20260711000002_unified_access_control.sql
  { key: '/network/process-level', kind: 'page', label: 'Process-Level Network', description: 'Process-level network view', sortOrder: 40 },  // 20260711000002_unified_access_control.sql
  { key: '/network/firm-level', kind: 'page', label: 'Firm-Level Network', description: 'Firm-level network view', sortOrder: 50 },  // 20260711000002_unified_access_control.sql
  { key: '/network/interactive-space', kind: 'page', label: 'Interactive Network Space', description: 'Interactive network exploration space', sortOrder: 60 },  // 20260711000002_unified_access_control.sql
  { key: '/policies', kind: 'page', label: 'Policies', description: 'Sourcing, inventory, transportation & fulfillment policies', sortOrder: 70 },  // 20260711000002_unified_access_control.sql
  { key: '/simulation-lab', kind: 'page', label: 'Simulation Lab', description: 'Scientific simulation experiments', sortOrder: 80 },  // 20260711000002_unified_access_control.sql
  { key: '/project-intelligence', kind: 'page', label: 'Project Intelligence', description: 'AI-powered project insights', sortOrder: 90 },  // 20260711000002_unified_access_control.sql
  { key: '/developer', kind: 'page', label: 'Developer API', description: 'API keys, scopes and quickstarts', sortOrder: 100 },  // 20260711000002_unified_access_control.sql
  { key: '/profile', kind: 'page', label: 'My Profile', description: 'Personal account settings (always available)', sortOrder: 110 },  // 20260711000002_unified_access_control.sql
  { key: '/admin', kind: 'page', label: 'Super Admin', description: 'Platform administration area', sortOrder: 120 },  // 20260711000002_unified_access_control.sql
];

export const FEATURE_CAPABILITIES: CapabilityMeta[] = [
  { key: 'ai_chat', kind: 'feature', label: 'AI Assistant', description: 'Use the AI chat assistant', sortOrder: 210 },  // 20260711000002_unified_access_control.sql
  { key: 'simulation_lab', kind: 'feature', label: 'Run Simulations', description: 'Configure and run simulation experiments', sortOrder: 220 },  // 20260711000002_unified_access_control.sql
  { key: 'project_intelligence', kind: 'feature', label: 'Project Intelligence', description: 'Generate AI project insights and analysis', sortOrder: 230 },  // 20260711000002_unified_access_control.sql
  { key: 'data_editing', kind: 'feature', label: 'Data Editing', description: 'Create and edit project data (item master, BOM, logistics)', sortOrder: 240 },  // 20260711000002_unified_access_control.sql
  { key: 'data_edit_inputs', kind: 'feature', label: 'Edit Input Data', description: 'Create and edit tier-2 project data — item master, BOM, logistics lanes', sortOrder: 241 },  // 20260915000005_project_membership_and_delegation.sql
  { key: 'data_edit_policies', kind: 'feature', label: 'Edit Policies', description: 'Create and edit tier-4 decisions — policies, overrides and scenarios', sortOrder: 242 },  // 20260915000005_project_membership_and_delegation.sql
  { key: 'export', kind: 'feature', label: 'Export', description: 'Export data, reports and simulation results', sortOrder: 250 },  // 20260711000002_unified_access_control.sql
  { key: 'agent_proposals', kind: 'feature', label: 'Agent Proposals', description: 'See AI proposal cards and receive routed agent drafts', sortOrder: 260 },  // 20260715000003_agent_capabilities.sql
  { key: 'agent_apply', kind: 'feature', label: 'Agent Apply', description: 'Approve/Reject proposal cards (i.e. cause gated mutations)', sortOrder: 270 },  // 20260715000003_agent_capabilities.sql
  { key: 'agent_data_steward', kind: 'feature', label: 'Data Steward Agent', description: 'Routing eligibility for the Data Steward (item-master diffs)', sortOrder: 280 },  // 20260715000003_agent_capabilities.sql
  { key: 'agent_policy_configurator', kind: 'feature', label: 'Policy Configurator Agent', description: 'Routing eligibility for the Policy Configurator (policy bundle diffs)', sortOrder: 290 },  // 20260715000003_agent_capabilities.sql
  { key: 'agent_vv_analyst', kind: 'feature', label: 'V&V Analyst Agent', description: 'Routing eligibility for the V&V Analyst (model-card drafts)', sortOrder: 300 },  // 20260715000003_agent_capabilities.sql
  { key: 'agent_experiment_designer', kind: 'feature', label: 'Experiment Designer Agent', description: 'Routing eligibility for the Experiment Designer (experiment specs)', sortOrder: 310 },  // 20260715000003_agent_capabilities.sql
  { key: 'agent_explainer', kind: 'feature', label: 'Explainer Agent', description: 'Routing eligibility for the Explainer (trace explanations)', sortOrder: 320 },  // 20260715000003_agent_capabilities.sql
  { key: 'chat_history_sync', kind: 'feature', label: 'Chat History Sync', description: 'Server-side chat threads: cross-device history, folders and search', sortOrder: 330 },  // 20260717000001_chat_store.sql
  { key: 'reports', kind: 'feature', label: 'Decision Reports', description: 'Render and download decision reports (XLSX/PDF) from the file workspace', sortOrder: 330 },  // 20260723000001_reports_and_file_workspace.sql
  { key: 'agent_report_builder', kind: 'feature', label: 'Report Builder Agent', description: 'Routing eligibility for the Report Builder (decision reports)', sortOrder: 340 },  // 20260723000001_reports_and_file_workspace.sql
  { key: 'project_memory', kind: 'feature', label: 'Project Memory', description: 'Consent-only project memory: saved facts/preferences/decisions cited to their source', sortOrder: 340 },  // 20260717000003_project_memory.sql
  { key: 'agent_cost_estimator', kind: 'feature', label: 'Cost Estimator Agent', description: 'Routing eligibility for the Cost Estimator (parameter estimates with uncertainty intervals)', sortOrder: 350 },  // 20260726193000_cost_estimator.sql
  { key: 'agent_network_cartographer', kind: 'feature', label: 'Network Cartographer Agent', description: 'Routing eligibility for the Network Cartographer (evidence-cited deep-tier network mapping)', sortOrder: 360 },  // 20260727000001_network_cartographer.sql
  { key: 'agent_disruption_sentinel', kind: 'feature', label: 'Disruption Sentinel Agent', description: 'Routing eligibility for the Disruption Sentinel (on-demand corroborated risk alerts with simulation-sized impact)', sortOrder: 370 },  // 20260729000001_disruption_sentinel.sql
];

export const FEATURE_KEYS: FeatureKey[] = FEATURE_CAPABILITIES.map((c) => c.key as FeatureKey);
