project_id = "wckdrutwkytwcomrlpib"

[functions.calculate-node-prominence]
verify_jwt = false

[functions.combine-project]
verify_jwt = true

[functions.delete-project]
verify_jwt = true

[functions.ingest-outbound-logistics]
verify_jwt = true

[functions.ingest-bom-multi-level]
verify_jwt = true

[functions.ingest-inbound-logistics]
verify_jwt = true

[functions.project-ai-chat]
verify_jwt = false

[functions.project-ai-health]
verify_jwt = false
