// GENERATED by scripts/data-contract/generate.mjs from the data contract.
// Do not edit by hand: `npm run contract:check` fails on drift.
//
// Phase 3 / WP 3.2 — the CSV ingestion spec. `ingest-file` parses and validates
// from this and from nothing else; every header, every required flag and every
// rule below is authored in supabase/contract/*.contract.yaml.
//
// PROMOTABLE_TARGETS must equal the list inside public.ingest_target_is_promotable()
// (20260916000015_ingest_landing.sql). `ingestSpecParity.test.ts` fails if they
// drift — the SQL cannot import this file, so the parity is checked instead of
// assumed.

export type IngestRule = {
  kind: 'text' | 'numeric' | 'integer' | 'unit' | 'enum' | 'boolean';
  min?: number;
  exclusive_min?: number;
  max?: number;
  values?: string[];
  /** What an empty cell means: land no value, or reject the row. */
  blank?: 'null' | 'reject';
};

export type IngestColumn = {
  column: string;
  csvHeader: string;
  required: boolean;
  type: string;
  nullable: boolean;
  rule: IngestRule;
  validate: string | null;
};

/**
 * WP 3.3 (I3) — one unit conversion the PROMOTION applies, so that nothing
 * downstream converts. `rate` is a quantity per unit-period (rate_to_weekly);
 * `duration` is a length of time (duration_to_weeks). They are not inverses.
 * After promotion the row's `unitColumn` reads `canonical`, so a tier-2 row
 * states its own unit instead of relying on a default (§5 T1).
 */
export type IngestNormalization = {
  column: string;
  unitColumn: string;
  conversion: 'rate' | 'duration';
  canonical: string;
};

export type IngestDataset = {
  /** The template id UploadWizard offers. */
  dataset: string;
  /** The tier-2 table a promoted row lands in. */
  target: string;
  tier: string;
  factClass: 'master' | 'transactional';
  /** Columns the server supplies from the project; a file may not carry them. */
  serverSet: string[];
  columns: IngestColumn[];
  /** Unit conversions the promotion applies; empty when the dataset has none. */
  normalize: IngestNormalization[];
};

export const INGEST_DATASETS: Record<string, IngestDataset> = {
  "bom_multi_level": {
    "dataset": "bom_multi_level",
    "target": "bom_multi_level",
    "tier": "2",
    "factClass": "master",
    "serverSet": [
      "project_id",
      "plant_name"
    ],
    "columns": [
      {
        "column": "material_id",
        "csvHeader": "material_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim — this ingest function is the correct pattern to copy"
      },
      {
        "column": "level",
        "csvHeader": "level",
        "required": true,
        "type": "integer",
        "nullable": false,
        "rule": {
          "kind": "integer",
          "min": 0,
          "blank": "reject"
        },
        "validate": "integer >= 0 — level 0 is a root component, which both live parsers admit and always have (WP 3.2 §16)"
      },
      {
        "column": "higher_level_component_id",
        "csvHeader": "higher_level_component_id",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "text",
          "blank": "null"
        },
        "validate": "may be blank only at the root level"
      },
      {
        "column": "consumption_rate",
        "csvHeader": "consumption_rate",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "reject"
        },
        "validate": "numeric > 0"
      }
    ],
    "normalize": []
  },
  "bom_single_level": {
    "dataset": "bom_single_level",
    "target": "bom_single_level",
    "tier": "2",
    "factClass": "master",
    "serverSet": [
      "project_id",
      "plant_name"
    ],
    "columns": [
      {
        "column": "product_id",
        "csvHeader": "product_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim — enforced here; ingest-bom-multi-level is the correct pattern"
      },
      {
        "column": "material_id",
        "csvHeader": "material_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim"
      },
      {
        "column": "consumption_rate",
        "csvHeader": "consumption_rate",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "reject"
        },
        "validate": "numeric > 0"
      }
    ],
    "normalize": []
  },
  "item_master_customers": {
    "dataset": "item_master_customers",
    "target": "customers",
    "tier": "2",
    "factClass": "master",
    "serverSet": [
      "project_id"
    ],
    "columns": [
      {
        "column": "customer_id",
        "csvHeader": "customer_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty; unique within the project"
      },
      {
        "column": "name",
        "csvHeader": "name",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "text",
          "blank": "null"
        },
        "validate": "optional; display only"
      },
      {
        "column": "segment",
        "csvHeader": "segment",
        "required": false,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "null"
        },
        "validate": "optional; any string. Blank lands NOTHING and the column's own DEFAULT 'default' stands in — which is a value and not an absence, so the landing reports it as a substitution rather than leaving the cell silent (T2)."
      },
      {
        "column": "priority_weight",
        "csvHeader": "priority_weight",
        "required": false,
        "type": "numeric",
        "nullable": false,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "blank": "null"
        },
        "validate": "optional; >= 0. ZERO IS ALLOWED AND MEANS SOMETHING: only the ratio between two customers matters, so 0 is the lowest priority there is — served last, and only out of what is left. `exclusive_min` would reject a value the engine reads correctly. Blank lands nothing and the DEFAULT 1.0 stands in, which makes the `priority` rule inert for that customer."
      }
    ],
    "normalize": []
  },
  "inbound_logistics": {
    "dataset": "inbound_logistics",
    "target": "inbound_logistics",
    "tier": "2",
    "factClass": "transactional",
    "serverSet": [
      "project_id",
      "plant_name"
    ],
    "columns": [
      {
        "column": "supplier_id",
        "csvHeader": "supplier_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim — NOT enforced today (D8)"
      },
      {
        "column": "material_id",
        "csvHeader": "material_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim — NOT enforced today (D8)"
      },
      {
        "column": "volume",
        "csvHeader": "volume",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "blank": "reject"
        },
        "validate": "numeric >= 0; blank becomes NULL, not 0 (D7)"
      },
      {
        "column": "time_unit",
        "csvHeader": "time_unit",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "unit",
          "blank": "null"
        },
        "validate": "one of day/week/month/quarter/year and their -ly spellings"
      },
      {
        "column": "lead_time",
        "csvHeader": "lead_time",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "reject"
        },
        "validate": "numeric > 0"
      },
      {
        "column": "unit_price",
        "csvHeader": "unit_price",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "reject"
        },
        "validate": "numeric > 0"
      },
      {
        "column": "lead_time_unit",
        "csvHeader": "lead_time_unit",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "unit",
          "blank": "null"
        },
        "validate": "one of the units public.unit_days() knows — enforced by the column's CHECK constraint"
      }
    ],
    "normalize": [
      {
        "column": "lead_time",
        "unitColumn": "lead_time_unit",
        "conversion": "duration",
        "canonical": "week"
      },
      {
        "column": "volume",
        "unitColumn": "time_unit",
        "conversion": "rate",
        "canonical": "week"
      }
    ]
  },
  "item_master_materials": {
    "dataset": "item_master_materials",
    "target": "materials",
    "tier": "2",
    "factClass": "master",
    "serverSet": [
      "project_id"
    ],
    "columns": [
      {
        "column": "material_id",
        "csvHeader": "material_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty; unique within the project"
      },
      {
        "column": "name",
        "csvHeader": "name",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "text",
          "blank": "null"
        },
        "validate": null
      },
      {
        "column": "cost",
        "csvHeader": "cost",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "null"
        },
        "validate": "numeric > 0"
      },
      {
        "column": "holding_cost_pct",
        "csvHeader": "holding_cost_pct",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "max": 1,
          "blank": "null"
        },
        "validate": "numeric in [0, 1]"
      },
      {
        "column": "moq",
        "csvHeader": "moq",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "blank": "null"
        },
        "validate": "numeric >= 0"
      },
      {
        "column": "initial_on_hand",
        "csvHeader": "initial_on_hand",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "blank": "null"
        },
        "validate": "numeric >= 0"
      },
      {
        "column": "lead_time_dist",
        "csvHeader": "lead_time_dist",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "enum",
          "values": [
            "deterministic",
            "lognormal",
            "gamma"
          ],
          "blank": "null"
        },
        "validate": "one of the LeadTimeDist enum values; `empirical` is reserved for the data-import path (M7) and is not selectable yet"
      },
      {
        "column": "lead_time_cv",
        "csvHeader": "lead_time_cv",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "blank": "null"
        },
        "validate": "numeric >= 0"
      }
    ],
    "normalize": []
  },
  "outbound_logistics": {
    "dataset": "outbound_logistics",
    "target": "outbound_logistics",
    "tier": "2",
    "factClass": "transactional",
    "serverSet": [
      "project_id",
      "plant_name"
    ],
    "columns": [
      {
        "column": "customer_id",
        "csvHeader": "customer_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim — NOT enforced today (D8)"
      },
      {
        "column": "product_id",
        "csvHeader": "product_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim — NOT enforced today (D8)"
      },
      {
        "column": "volume",
        "csvHeader": "volume",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "blank": "reject"
        },
        "validate": "numeric >= 0; blank becomes NULL, not 0 (D7)"
      },
      {
        "column": "time_unit",
        "csvHeader": "time_unit",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "unit",
          "blank": "null"
        },
        "validate": "one of day/week/month/quarter/year and their -ly spellings"
      },
      {
        "column": "expected_lead_time",
        "csvHeader": "expected_lead_time",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "reject"
        },
        "validate": "numeric > 0"
      },
      {
        "column": "unit_price",
        "csvHeader": "unit_price",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "reject"
        },
        "validate": "numeric > 0"
      }
    ],
    "normalize": [
      {
        "column": "volume",
        "unitColumn": "time_unit",
        "conversion": "rate",
        "canonical": "week"
      }
    ]
  },
  "item_master_products": {
    "dataset": "item_master_products",
    "target": "products",
    "tier": "2",
    "factClass": "master",
    "serverSet": [
      "project_id"
    ],
    "columns": [
      {
        "column": "product_id",
        "csvHeader": "product_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty; unique within the project"
      },
      {
        "column": "name",
        "csvHeader": "name",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "text",
          "blank": "null"
        },
        "validate": null
      },
      {
        "column": "sell_price",
        "csvHeader": "sell_price",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "null"
        },
        "validate": "numeric > 0"
      },
      {
        "column": "production_capacity",
        "csvHeader": "production_capacity",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "null"
        },
        "validate": "numeric > 0"
      },
      {
        "column": "fulfillment_mode",
        "csvHeader": "fulfillment_mode",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "enum",
          "values": [
            "mto",
            "mts"
          ],
          "blank": "null"
        },
        "validate": "mto or mts; ato is a reserved enum that hard-errors, eto/cto are UI labels only"
      },
      {
        "column": "demand_distribution",
        "csvHeader": "demand_distribution",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "enum",
          "values": [
            "triangular",
            "deterministic",
            "poisson",
            "negbin"
          ],
          "blank": "null"
        },
        "validate": null
      },
      {
        "column": "demand_mean",
        "csvHeader": "demand_mean",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "null"
        },
        "validate": "numeric > 0"
      },
      {
        "column": "demand_cv",
        "csvHeader": "demand_cv",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "blank": "null"
        },
        "validate": "numeric >= 0"
      },
      {
        "column": "demand_min",
        "csvHeader": "demand_min",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "blank": "null"
        },
        "validate": "numeric >= 0"
      },
      {
        "column": "demand_max",
        "csvHeader": "demand_max",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "blank": "null"
        },
        "validate": "numeric >= 0"
      }
    ],
    "normalize": []
  },
  "item_master_suppliers": {
    "dataset": "item_master_suppliers",
    "target": "suppliers",
    "tier": "2",
    "factClass": "master",
    "serverSet": [
      "project_id"
    ],
    "columns": [
      {
        "column": "supplier_id",
        "csvHeader": "supplier_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty; unique within the project"
      },
      {
        "column": "name",
        "csvHeader": "name",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "text",
          "blank": "null"
        },
        "validate": null
      },
      {
        "column": "capacity_per_week",
        "csvHeader": "capacity_per_week",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "null"
        },
        "validate": "numeric > 0 when present"
      },
      {
        "column": "reliability_score",
        "csvHeader": "reliability_score",
        "required": false,
        "type": "numeric",
        "nullable": false,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "max": 1,
          "blank": "null"
        },
        "validate": "numeric in (0, 1]"
      }
    ],
    "normalize": []
  },
  "tier2_suppliers": {
    "dataset": "tier2_suppliers",
    "target": "tier2_suppliers",
    "tier": "2",
    "factClass": "transactional",
    "serverSet": [
      "project_id",
      "plant_name"
    ],
    "columns": [
      {
        "column": "supplier_id",
        "csvHeader": "supplier_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim"
      },
      {
        "column": "upstream_supplier_id",
        "csvHeader": "upstream_supplier_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim"
      },
      {
        "column": "material_id",
        "csvHeader": "material_id",
        "required": true,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim"
      },
      {
        "column": "relationship_type",
        "csvHeader": "relationship_type",
        "required": true,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "free text; no closed vocabulary exists for it"
      },
      {
        "column": "volume",
        "csvHeader": "volume",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "blank": "null"
        },
        "validate": "numeric >= 0; blank lands no value, never 0 (D7)"
      },
      {
        "column": "unit_price",
        "csvHeader": "unit_price",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "null"
        },
        "validate": "numeric > 0; blank lands no value"
      },
      {
        "column": "lead_time",
        "csvHeader": "lead_time",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "null"
        },
        "validate": "numeric > 0; blank lands no value"
      },
      {
        "column": "time_unit",
        "csvHeader": "time_unit",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "unit",
          "blank": "null"
        },
        "validate": "one of the units public.unit_days() knows; blank means weeks"
      }
    ],
    "normalize": [
      {
        "column": "volume",
        "unitColumn": "time_unit",
        "conversion": "rate",
        "canonical": "week"
      }
    ]
  },
  "tier3_suppliers": {
    "dataset": "tier3_suppliers",
    "target": "tier3_suppliers",
    "tier": "2",
    "factClass": "transactional",
    "serverSet": [
      "project_id",
      "plant_name"
    ],
    "columns": [
      {
        "column": "supplier_id",
        "csvHeader": "supplier_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim"
      },
      {
        "column": "upstream_supplier_id",
        "csvHeader": "upstream_supplier_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim"
      },
      {
        "column": "material_id",
        "csvHeader": "material_id",
        "required": true,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim"
      },
      {
        "column": "relationship_type",
        "csvHeader": "relationship_type",
        "required": true,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "free text; no closed vocabulary exists for it"
      },
      {
        "column": "volume",
        "csvHeader": "volume",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "blank": "null"
        },
        "validate": "numeric >= 0; blank lands no value, never 0 (D7)"
      },
      {
        "column": "unit_price",
        "csvHeader": "unit_price",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "null"
        },
        "validate": "numeric > 0; blank lands no value"
      },
      {
        "column": "lead_time",
        "csvHeader": "lead_time",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "null"
        },
        "validate": "numeric > 0; blank lands no value"
      },
      {
        "column": "time_unit",
        "csvHeader": "time_unit",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "unit",
          "blank": "null"
        },
        "validate": "one of the units public.unit_days() knows; blank means weeks"
      }
    ],
    "normalize": [
      {
        "column": "volume",
        "unitColumn": "time_unit",
        "conversion": "rate",
        "canonical": "week"
      }
    ]
  }
};

export const PROMOTABLE_TARGETS: string[] = [
  "bom_multi_level",
  "bom_single_level",
  "customers",
  "inbound_logistics",
  "materials",
  "outbound_logistics",
  "products",
  "suppliers",
  "tier2_suppliers",
  "tier3_suppliers"
];
