// GENERATED by scripts/data-contract/generate.mjs from the data contract.
// Do not edit by hand: `npm run contract:check` fails on drift.
//
// Phase 3 / WP 3.2 — the CSV ingestion spec. `ingest-file` parses and validates
// from this and from nothing else; every header, every required flag and every
// rule below is authored in supabase/contract/*.contract.yaml.
//
// PROMOTABLE_TARGETS must equal the list inside public.ingest_target_is_promotable()
// (20260916000015_ingest_landing.sql). `ingestSpecParity.test.ts` fails if they
// drift — the SQL cannot import this file, so the parity is checked instead of
// assumed.

export type IngestRule = {
  kind: 'text' | 'numeric' | 'integer' | 'unit' | 'enum' | 'boolean';
  min?: number;
  exclusive_min?: number;
  max?: number;
  values?: string[];
  /** What an empty cell means: land no value, or reject the row. */
  blank?: 'null' | 'reject';
};

export type IngestColumn = {
  column: string;
  csvHeader: string;
  required: boolean;
  type: string;
  nullable: boolean;
  rule: IngestRule;
  validate: string | null;
};

export type IngestDataset = {
  /** The template id UploadWizard offers. */
  dataset: string;
  /** The tier-2 table a promoted row lands in. */
  target: string;
  tier: string;
  factClass: 'master' | 'transactional';
  /** Columns the server supplies from the project; a file may not carry them. */
  serverSet: string[];
  columns: IngestColumn[];
};

export const INGEST_DATASETS: Record<string, IngestDataset> = {
  "bom_multi_level": {
    "dataset": "bom_multi_level",
    "target": "bom_multi_level",
    "tier": "2",
    "factClass": "master",
    "serverSet": [
      "project_id",
      "plant_name"
    ],
    "columns": [
      {
        "column": "material_id",
        "csvHeader": "material_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim — this ingest function is the correct pattern to copy"
      },
      {
        "column": "level",
        "csvHeader": "level",
        "required": true,
        "type": "integer",
        "nullable": false,
        "rule": {
          "kind": "integer",
          "min": 0,
          "blank": "reject"
        },
        "validate": "integer >= 0 — level 0 is a root component, which both live parsers admit and always have (WP 3.2 §16)"
      },
      {
        "column": "higher_level_component_id",
        "csvHeader": "higher_level_component_id",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "text",
          "blank": "null"
        },
        "validate": "may be blank only at the root level"
      },
      {
        "column": "consumption_rate",
        "csvHeader": "consumption_rate",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "reject"
        },
        "validate": "numeric > 0"
      }
    ]
  },
  "bom_single_level": {
    "dataset": "bom_single_level",
    "target": "bom_single_level",
    "tier": "2",
    "factClass": "master",
    "serverSet": [
      "project_id",
      "plant_name"
    ],
    "columns": [
      {
        "column": "product_id",
        "csvHeader": "product_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim — enforced here; ingest-bom-multi-level is the correct pattern"
      },
      {
        "column": "material_id",
        "csvHeader": "material_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim"
      },
      {
        "column": "consumption_rate",
        "csvHeader": "consumption_rate",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "reject"
        },
        "validate": "numeric > 0"
      }
    ]
  },
  "inbound_logistics": {
    "dataset": "inbound_logistics",
    "target": "inbound_logistics",
    "tier": "2",
    "factClass": "transactional",
    "serverSet": [
      "project_id",
      "plant_name"
    ],
    "columns": [
      {
        "column": "supplier_id",
        "csvHeader": "supplier_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim — NOT enforced today (D8)"
      },
      {
        "column": "material_id",
        "csvHeader": "material_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim — NOT enforced today (D8)"
      },
      {
        "column": "volume",
        "csvHeader": "volume",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "blank": "reject"
        },
        "validate": "numeric >= 0; blank becomes NULL, not 0 (D7)"
      },
      {
        "column": "time_unit",
        "csvHeader": "time_unit",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "unit",
          "blank": "null"
        },
        "validate": "one of day/week/month/quarter/year and their -ly spellings"
      },
      {
        "column": "lead_time",
        "csvHeader": "lead_time",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "reject"
        },
        "validate": "numeric > 0"
      },
      {
        "column": "unit_price",
        "csvHeader": "unit_price",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "reject"
        },
        "validate": "numeric > 0"
      },
      {
        "column": "lead_time_unit",
        "csvHeader": "lead_time_unit",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "unit",
          "blank": "null"
        },
        "validate": "one of the units public.unit_days() knows — enforced by the column's CHECK constraint"
      }
    ]
  },
  "outbound_logistics": {
    "dataset": "outbound_logistics",
    "target": "outbound_logistics",
    "tier": "2",
    "factClass": "transactional",
    "serverSet": [
      "project_id",
      "plant_name"
    ],
    "columns": [
      {
        "column": "customer_id",
        "csvHeader": "customer_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim — NOT enforced today (D8)"
      },
      {
        "column": "product_id",
        "csvHeader": "product_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim — NOT enforced today (D8)"
      },
      {
        "column": "volume",
        "csvHeader": "volume",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "blank": "reject"
        },
        "validate": "numeric >= 0; blank becomes NULL, not 0 (D7)"
      },
      {
        "column": "time_unit",
        "csvHeader": "time_unit",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "unit",
          "blank": "null"
        },
        "validate": "one of day/week/month/quarter/year and their -ly spellings"
      },
      {
        "column": "expected_lead_time",
        "csvHeader": "expected_lead_time",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "reject"
        },
        "validate": "numeric > 0"
      },
      {
        "column": "unit_price",
        "csvHeader": "unit_price",
        "required": true,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "reject"
        },
        "validate": "numeric > 0"
      }
    ]
  },
  "tier2_suppliers": {
    "dataset": "tier2_suppliers",
    "target": "tier2_suppliers",
    "tier": "2",
    "factClass": "transactional",
    "serverSet": [
      "project_id",
      "plant_name"
    ],
    "columns": [
      {
        "column": "supplier_id",
        "csvHeader": "supplier_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim"
      },
      {
        "column": "upstream_supplier_id",
        "csvHeader": "upstream_supplier_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim"
      },
      {
        "column": "material_id",
        "csvHeader": "material_id",
        "required": true,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim"
      },
      {
        "column": "relationship_type",
        "csvHeader": "relationship_type",
        "required": true,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "free text; no closed vocabulary exists for it"
      },
      {
        "column": "volume",
        "csvHeader": "volume",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "blank": "null"
        },
        "validate": "numeric >= 0; blank lands no value, never 0 (D7)"
      },
      {
        "column": "unit_price",
        "csvHeader": "unit_price",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "null"
        },
        "validate": "numeric > 0; blank lands no value"
      },
      {
        "column": "lead_time",
        "csvHeader": "lead_time",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "null"
        },
        "validate": "numeric > 0; blank lands no value"
      },
      {
        "column": "time_unit",
        "csvHeader": "time_unit",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "unit",
          "blank": "null"
        },
        "validate": "one of the units public.unit_days() knows; blank means weeks"
      }
    ]
  },
  "tier3_suppliers": {
    "dataset": "tier3_suppliers",
    "target": "tier3_suppliers",
    "tier": "2",
    "factClass": "transactional",
    "serverSet": [
      "project_id",
      "plant_name"
    ],
    "columns": [
      {
        "column": "supplier_id",
        "csvHeader": "supplier_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim"
      },
      {
        "column": "upstream_supplier_id",
        "csvHeader": "upstream_supplier_id",
        "required": true,
        "type": "text",
        "nullable": false,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim"
      },
      {
        "column": "material_id",
        "csvHeader": "material_id",
        "required": true,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "non-empty after trim"
      },
      {
        "column": "relationship_type",
        "csvHeader": "relationship_type",
        "required": true,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "text",
          "blank": "reject"
        },
        "validate": "free text; no closed vocabulary exists for it"
      },
      {
        "column": "volume",
        "csvHeader": "volume",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "min": 0,
          "blank": "null"
        },
        "validate": "numeric >= 0; blank lands no value, never 0 (D7)"
      },
      {
        "column": "unit_price",
        "csvHeader": "unit_price",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "null"
        },
        "validate": "numeric > 0; blank lands no value"
      },
      {
        "column": "lead_time",
        "csvHeader": "lead_time",
        "required": false,
        "type": "numeric",
        "nullable": true,
        "rule": {
          "kind": "numeric",
          "exclusive_min": 0,
          "blank": "null"
        },
        "validate": "numeric > 0; blank lands no value"
      },
      {
        "column": "time_unit",
        "csvHeader": "time_unit",
        "required": false,
        "type": "text",
        "nullable": true,
        "rule": {
          "kind": "unit",
          "blank": "null"
        },
        "validate": "one of the units public.unit_days() knows; blank means weeks"
      }
    ]
  }
};

export const PROMOTABLE_TARGETS: string[] = [
  "bom_multi_level",
  "bom_single_level",
  "inbound_logistics",
  "outbound_logistics",
  "tier2_suppliers",
  "tier3_suppliers"
];
