import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  FEATURE_CAPABILITIES,
  PAGE_CAPABILITIES,
  roleFallbackCapabilities,
} from "../../capabilities";

/**
 * D33 — ONE CAPABILITY CATALOG.
 *
 * `public.capabilities` is seeded across nine migrations and the client needs
 * the same keys without a round trip. That is I1 (`single-source`) in the access
 * layer, and until WP 3.0 nothing checked the two agreed. The generator
 * (`npm run contract:capabilities`) now writes `capabilities.generated.ts` out
 * of the migrations and `contract:check` fails on drift; these tests cover the
 * half a generator cannot, which is the hand-written ROLE FALLBACK.
 *
 * It had drifted, and this file is what would have caught it: `reports` and
 * `agent_report_builder` shipped in 20260723000001 and never reached
 * `roleFallbackCapabilities`, so every user holding Decision Reports lost the
 * feature whenever the capability fetch failed — a denial nobody would have
 * traced back to a missing key in an object literal.
 */
describe("the capability catalog has one author", () => {
  const generated = readFileSync(
    join(process.cwd(), "src/lib/capabilities.generated.ts"),
    "utf8",
  );

  it("is generated, and says so", () => {
    expect(generated.startsWith("// GENERATED by")).toBe(true);
    expect(generated).toContain("DO NOT EDIT");
  });

  it("carries every key back to the migration that seeds it", () => {
    for (const cap of [...PAGE_CAPABILITIES, ...FEATURE_CAPABILITIES]) {
      const line = generated
        .split("\n")
        .find((l) => l.includes(`key: '${cap.key}'`));
      expect(line, `${cap.key} has no generated entry`).toBeDefined();
      expect(line, `${cap.key} does not name its seeding migration`).toMatch(
        /\/\/ \d{14}_[\w-]+\.sql$/,
      );
    }
  });

  it("is not empty in either kind", () => {
    expect(PAGE_CAPABILITIES.length).toBeGreaterThan(0);
    expect(FEATURE_CAPABILITIES.length).toBeGreaterThan(0);
  });
});

describe("the role fallback covers the whole catalog", () => {
  // The fallback is what resolves when `get_my_capabilities` fails. A key it
  // does not name reads as `false`, which revokes a capability the database
  // grants — a silent denial, exactly the failure mode `declared-fallback` (I6)
  // exists to stop.
  for (const role of ["super_admin", "admin", "modeler", "user"] as const) {
    it(`${role}: every feature key has an explicit fallback value`, () => {
      const caps = roleFallbackCapabilities(role);
      for (const { key } of FEATURE_CAPABILITIES) {
        expect(
          Object.prototype.hasOwnProperty.call(caps.features, key),
          `${key} is missing from roleFallbackCapabilities — it would resolve to false`,
        ).toBe(true);
        expect(typeof caps.features[key]).toBe("boolean");
      }
    });

    it(`${role}: the fallback invents no capability the catalog lacks`, () => {
      const known = new Set(FEATURE_CAPABILITIES.map((c) => c.key));
      for (const key of Object.keys(roleFallbackCapabilities(role).features)) {
        expect(known.has(key), `${key} is offered by the fallback and seeded by nothing`).toBe(
          true,
        );
      }
    });

    it(`${role}: every page key has an explicit fallback value`, () => {
      const caps = roleFallbackCapabilities(role);
      for (const { key } of PAGE_CAPABILITIES) {
        expect(
          Object.prototype.hasOwnProperty.call(caps.pages, key),
          `${key} is missing from the page fallback`,
        ).toBe(true);
      }
    });
  }
});
