// Layer B agent-turn runner + persona-handoff helpers — Stage 1
// (ai-agents.md §3.3, §6.4). index.ts stays the orchestrator; this module
// holds the mechanics so the deterministic eval tier can drive them with
// scripted providers and stubbed project data.
//
// Statelessness law (§3.4-5, §6.4): the agent turn receives ONLY the routed
// utterance and its deterministic grounding context — no chat history, no
// rolling summary. The persona wrap-up turn receives the agent's short report
// and produces the user-facing sentences; the {kind:"proposal"} part is
// attached mechanically by the orchestrator, never generated by an LLM.

import { runChat, type ChatRunResult } from "./providers.ts";
import type { ToolContext } from "./tools.ts";
import {
  buildStewardContext,
  stewardToolDeclarations,
  STEWARD_AGENT_ID,
  type ProposalPartData,
} from "./draftTools.ts";

export interface AgentTurnResult {
  /** false only when the agent turn itself failed (provider error/blocked). */
  ok: boolean;
  /** The agent's own 2-4 sentence report (§5.1 template) — the wrap-up input. */
  reply: string;
  /** The mechanically-attached card part, when a proposal was drafted. */
  proposalPart: { kind: "proposal"; data: ProposalPartData } | null;
  toolCalls: ChatRunResult["toolCalls"];
  /** One-line failure description for the §6.2 step-5 mixed-failure note. */
  error: string | null;
}

/**
 * One Data Steward turn through the shared runChat loop (bridge 1): §5.1
 * system prompt + least-privilege tool subset, empty history, same MAX_HOPS.
 */
export async function runDataStewardTurn(args: {
  modelId: string | undefined | null;
  utterance: string;
  ctx: ToolContext; // must carry ctx.draft (attribution + agent_proposals)
}): Promise<AgentTurnResult> {
  try {
    const system = await buildStewardContext(args.ctx, {
      utterance: args.utterance,
      userEmail: args.ctx.draft?.userEmail ?? null,
    });
    const result = await runChat(args.modelId, args.utterance.slice(0, 4000), [], args.ctx, null, {
      system,
      tools: stewardToolDeclarations,
    });
    const proposalPart = (result.parts ?? []).find((p) => p.kind === "proposal") as
      | { kind: "proposal"; data: ProposalPartData }
      | undefined;
    return {
      ok: !result.blocked,
      reply: result.reply ?? "",
      proposalPart: proposalPart ?? null,
      toolCalls: result.toolCalls ?? [],
      error: result.blocked ? "the draft request was blocked by the model provider" : null,
    };
  } catch (e) {
    const msg = e instanceof Error ? e.message : "agent turn failed";
    console.error(`[agent:${STEWARD_AGENT_ID}] turn failed:`, msg);
    return { ok: false, reply: "", proposalPart: null, toolCalls: [], error: msg };
  }
}

/** §6.4: the persona wrap-up turn's (server-internal) input — the agent's
 * report + proposal id; the persona produces the user-facing sentences. */
export function buildWrapupMessage(args: {
  utterance: string;
  agentReply: string;
  proposal: ProposalPartData | null;
}): string {
  const proposalLine = args.proposal
    ? `A proposal card was ${args.proposal.duplicate ? "already on file and re-used" : "created"}: ` +
      `"${args.proposal.title}" (status: ${args.proposal.status}; ${args.proposal.summary}). ` +
      `The card is attached to your reply automatically — do not describe its contents as applied.`
    : "No proposal card was created.";
  return `[internal handoff — this is not a user message]
The user asked: "${args.utterance.slice(0, 2000)}"
The Data Steward agent handled it and reported:
"${(args.agentReply || "(no report)").slice(0, 2000)}"
${proposalLine}
Write the user-facing reply in your own voice, 1-3 sentences: relay what the
draft covers and what is still missing, and — if a card exists — remind the
user to review and approve it before anything applies. Do not invent numbers
or details beyond the agent's report.`;
}

/** §6.2 step 5: one appended sentence for the mixed route (deterministic —
 * the advisory answer must survive an agent failure). */
export function mixedHandoffNote(agent: AgentTurnResult): string {
  if (agent.proposalPart) {
    return "I've also drafted the change you asked for — review the proposal card below and approve it before anything applies.";
  }
  if (!agent.ok) {
    return `I couldn't draft the change you asked for: ${agent.error ?? "the drafting step failed"}.`;
  }
  return agent.reply || "I couldn't draft the change — nothing in the project data grounds it yet.";
}
