// Layer B agent-turn runner + persona-handoff helpers — Stages 1–3
// (ai-agents.md §3.3, §6.4). index.ts stays the orchestrator; this module
// holds the mechanics so the deterministic eval tier can drive them with
// scripted providers and stubbed project data.
//
// Statelessness law (§3.4-5, §6.4): the agent turn receives ONLY the routed
// utterance and its deterministic grounding context — no chat history, no
// rolling summary. (Project memory is NOT chat memory: §14.4 admits it as a
// user-approved project artifact, appended by the context builders under the
// 8 KB budget when PROJECT_MEMORY_ENABLED.) The persona wrap-up turn receives
// the agent's short report and produces the user-facing sentences; the
// {kind:"proposal"} part is attached mechanically by the orchestrator, never
// generated by an LLM.
//
// Importing this module registers every staged draft tool into the shared
// executeTool registry (bridge 2): B1 via draftTools.ts, B2 via
// configuratorTools.ts, B3 via vvTools.ts, B4 via experimentTools.ts,
// B6 via reportTools.ts, get_project_memory via memory.ts.

import { runChat, type ChatRunResult, type RunChatOptions } from "./providers.ts";
import type { ToolContext, ToolDeclaration } from "./tools.ts";
import {
  buildStewardContext,
  stewardToolDeclarations,
  STEWARD_AGENT_ID,
  type ProposalPartData,
} from "./draftTools.ts";
import {
  buildConfiguratorContext,
  CONFIGURATOR_AGENT_ID,
  configuratorToolDeclarations,
} from "./configuratorTools.ts";
import { buildVvContext, VV_AGENT_ID, vvToolDeclarations } from "./vvTools.ts";
import {
  buildExperimentContext,
  EXPERIMENT_AGENT_ID,
  experimentToolDeclarations,
} from "./experimentTools.ts";
import {
  buildReportContext,
  REPORT_AGENT_ID,
  reportToolDeclarations,
} from "./reportTools.ts";
import {
  buildEstimatorContext,
  ESTIMATOR_AGENT_ID,
  estimatorToolDeclarations,
} from "./estimatorTools.ts";
import {
  buildCartographerContext,
  CARTOGRAPHER_AGENT_ID,
  cartographerToolDeclarationList,
} from "./cartographerTools.ts";
import {
  buildSentinelContext,
  SENTINEL_AGENT_ID,
  sentinelToolDeclarations,
} from "./sentinelTools.ts";
import { getProjectMemoryDeclaration, memoryEnabled } from "./memory.ts";

export interface AgentTurnResult {
  /** false only when the agent turn itself failed (provider error/blocked). */
  ok: boolean;
  /** The agent's own short report (§5 templates) — the wrap-up input. */
  reply: string;
  /** The mechanically-attached card part, when a proposal was drafted. */
  proposalPart: { kind: "proposal"; data: ProposalPartData } | null;
  toolCalls: ChatRunResult["toolCalls"];
  /** One-line failure description for the §6.2 step-5 mixed-failure note. */
  error: string | null;
}

interface AgentSpec {
  /** Human name for the §6.4 wrap-up handoff. */
  name: string;
  buildContext: (ctx: ToolContext, args: { utterance: string; userEmail: string | null }) => Promise<string>;
  tools: () => ReadonlyArray<ToolDeclaration>;
}

/** The turnable roster — one §5 spec per GA'd stage. B5 joins with its stage
 * (facet-11 traces, §9.6); an agent absent here can be routed to but never
 * run (index.ts falls back to advisory). */
export const AGENT_TURNS: Record<string, AgentSpec> = {
  [STEWARD_AGENT_ID]: {
    name: "Data Steward",
    buildContext: (ctx, args) => buildStewardContext(ctx, args),
    // §14.4: get_project_memory joins every agent's surface when M2 is on.
    tools: () => [
      ...stewardToolDeclarations,
      ...(memoryEnabled() ? [getProjectMemoryDeclaration] : []),
    ],
  },
  [ESTIMATOR_AGENT_ID]: {
    name: "Cost Estimator",
    buildContext: (ctx, args) => buildEstimatorContext(ctx, args),
    // §14.4: get_project_memory joins every agent's surface when M2 is on.
    tools: () => [
      ...estimatorToolDeclarations,
      ...(memoryEnabled() ? [getProjectMemoryDeclaration] : []),
    ],
  },
  [CARTOGRAPHER_AGENT_ID]: {
    name: "Network Cartographer",
    buildContext: (ctx, args) => buildCartographerContext(ctx, args),
    // §14.4: get_project_memory joins every agent's surface when M2 is on.
    // §18.2 v2: get_bom_rate_estimates joins only under
    // CARTOGRAPHER_PRODUCT_LEVEL (flag off ⇒ byte-identical v1 surface).
    tools: () => [
      ...cartographerToolDeclarationList(),
      ...(memoryEnabled() ? [getProjectMemoryDeclaration] : []),
    ],
  },
  [SENTINEL_AGENT_ID]: {
    name: "Disruption Sentinel",
    buildContext: (ctx, args) => buildSentinelContext(ctx, args),
    // §14.4: get_project_memory joins every agent's surface when M2 is on.
    tools: () => [
      ...sentinelToolDeclarations,
      ...(memoryEnabled() ? [getProjectMemoryDeclaration] : []),
    ],
  },
  [CONFIGURATOR_AGENT_ID]: {
    name: "Policy Configurator",
    buildContext: (ctx, args) => buildConfiguratorContext(ctx, args),
    tools: () => configuratorToolDeclarations(),
  },
  [VV_AGENT_ID]: {
    name: "V&V Analyst",
    buildContext: (ctx, args) => buildVvContext(ctx, args),
    tools: () => vvToolDeclarations(),
  },
  [EXPERIMENT_AGENT_ID]: {
    name: "Experiment Designer",
    buildContext: (ctx, args) => buildExperimentContext(ctx, args),
    tools: () => experimentToolDeclarations(),
  },
  [REPORT_AGENT_ID]: {
    name: "Report Builder",
    buildContext: (ctx, args) => buildReportContext(ctx, args),
    tools: () => reportToolDeclarations(),
  },
};

/**
 * One Layer B agent turn through the shared runChat loop (bridge 1): the §5
 * system prompt + the agent's least-privilege tool subset, empty history,
 * same MAX_HOPS.
 */
export async function runAgentTurn(args: {
  agentId: string;
  modelId: string | undefined | null;
  utterance: string;
  ctx: ToolContext; // must carry ctx.draft (attribution + agent_proposals)
  /** H1 (§22.3): envelope collector for the pre-send verifier's grounded
   * vocabulary. Absent ⇒ zero behavior change. */
  onToolResult?: RunChatOptions["onToolResult"];
  /** H1 (§22.3): hands the built CONTEXT/system text to the verifier (the
   * CONTEXT block's serialized artifacts ground the agent's claims). */
  onContext?: (contextText: string) => void;
  /** §22.3 corrective retry on the H3 resume path (where the agent's reply IS
   * the user-facing answer): the verifier's violation addendum, appended
   * after the agent system prompt. Never set outside that single retry. */
  systemAddendum?: string;
}): Promise<AgentTurnResult> {
  const spec = AGENT_TURNS[args.agentId];
  if (!spec) {
    return { ok: false, reply: "", proposalPart: null, toolCalls: [], error: `agent ${args.agentId} has no turn runner` };
  }
  try {
    const system = await spec.buildContext(args.ctx, {
      utterance: args.utterance,
      userEmail: args.ctx.draft?.userEmail ?? null,
    });
    args.onContext?.(system);
    const result = await runChat(args.modelId, args.utterance.slice(0, 4000), [], args.ctx, null, {
      system,
      tools: spec.tools(),
      ...(args.onToolResult ? { onToolResult: args.onToolResult } : {}),
      ...(args.systemAddendum ? { systemAddendum: args.systemAddendum } : {}),
      // §21.5 (H3): the agent turn spends the same request meters the
      // orchestrator created — absent ⇒ unmetered (eval direct drives).
      ...(args.ctx.budget ? { budget: args.ctx.budget } : {}),
    });
    const proposalPart = (result.parts ?? []).find((p) => p.kind === "proposal") as
      | { kind: "proposal"; data: ProposalPartData }
      | undefined;
    return {
      ok: !result.blocked,
      reply: result.reply ?? "",
      proposalPart: proposalPart ?? null,
      toolCalls: result.toolCalls ?? [],
      error: result.blocked ? "the draft request was blocked by the model provider" : null,
    };
  } catch (e) {
    const msg = e instanceof Error ? e.message : "agent turn failed";
    console.error(`[agent:${args.agentId}] turn failed:`, msg);
    return { ok: false, reply: "", proposalPart: null, toolCalls: [], error: msg };
  }
}

/** Stage 1 signature kept for the shipped suite (data_steward_test.ts). */
export function runDataStewardTurn(args: {
  modelId: string | undefined | null;
  utterance: string;
  ctx: ToolContext;
}): Promise<AgentTurnResult> {
  return runAgentTurn({ agentId: STEWARD_AGENT_ID, ...args });
}

/** §6.4: the persona wrap-up turn's (server-internal) input — the agent's
 * report + proposal id; the persona produces the user-facing sentences. */
export function buildWrapupMessage(args: {
  utterance: string;
  agentReply: string;
  proposal: ProposalPartData | null;
  agentName?: string;
}): string {
  const proposalLine = args.proposal
    ? `A proposal card was ${args.proposal.duplicate ? "already on file and re-used" : "created"}: ` +
      `"${args.proposal.title}" (status: ${args.proposal.status}; ${args.proposal.summary}). ` +
      `The card is attached to your reply automatically — do not describe its contents as applied.`
    : "No proposal card was created.";
  return `[internal handoff — this is not a user message]
The user asked: "${args.utterance.slice(0, 2000)}"
The ${args.agentName ?? "Data Steward"} agent handled it and reported:
"${(args.agentReply || "(no report)").slice(0, 2000)}"
${proposalLine}
Write the user-facing reply in your own voice, 1-3 sentences: relay what the
draft covers and what is still missing, and — if a card exists — remind the
user to review and approve it before anything applies. Do not invent numbers
or details beyond the agent's report.`;
}

/** §6.2 step 5: one appended sentence for the mixed route (deterministic —
 * the advisory answer must survive an agent failure). */
export function mixedHandoffNote(agent: AgentTurnResult): string {
  if (agent.proposalPart) {
    return "I've also drafted the change you asked for — review the proposal card below and approve it before anything applies.";
  }
  if (!agent.ok) {
    return `I couldn't draft the change you asked for: ${agent.error ?? "the drafting step failed"}.`;
  }
  return agent.reply || "I couldn't draft the change — nothing in the project data grounds it yet.";
}
