/**
 * Read the typed node projection — Phase 8 / WP 8.3 / §4 D112.
 *
 * THE ONE PLACE A PAGE GETS A NODE'S TYPE FROM. `node_list.echelon` is authored
 * once by `classify_node_echelon` (WP 8.1) and reached through
 * `get_graph_nodes` (WP 8.3, `20260919000002`), which exists because
 * `get_node_list`'s fixed `RETURNS TABLE` could not carry the new columns and
 * `CREATE OR REPLACE` cannot change a return type.
 *
 * A page that uses this hook does not classify anything. That is the point: the
 * eight classifiers §4 D112 counts all existed because there was nothing to read.
 */
import { useCallback, useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { asEchelon, type Echelon } from './types';

/** One row of the typed projection, narrowed. */
export interface TypedNode {
  id: string;
  label: string;
  /** `null` means the database has not derived it. NOT a licence to guess one. */
  echelon: Echelon | null;
  bomDepth: number | null;
  supplyTier: number | null;
  plantName: string | null;
  locationText: string | null;
  longitude: number | null;
  latitude: number | null;
}

export interface GraphNodesState {
  nodes: TypedNode[];
  byId: Map<string, TypedNode>;
  loading: boolean;
  /** A read error, surfaced so a page can SAY it failed rather than render empty. */
  error: string | null;
  /**
   * How many rows came back with no echelon. Published rather than hidden, because
   * a page that silently defaults them is what T1 forbids and what
   * `ProductLevelNetwork` does today (an unrecognised group becomes **Supplier**).
   * §15 found 29 such rows on the project a user reported, and zero elsewhere.
   */
  untypedCount: number;
  refresh: () => void;
}

/**
 * `get_graph_nodes` is absent from `src/integrations/supabase/types.ts`, which is
 * generated by the Supabase CLI and lists exactly two RPCs — it has been stale
 * since long before this package. Nine call sites in this repository already work
 * around it, and the established shape is `(supabase as any).rpc(...)`.
 *
 * This is the same escape hatch WITHOUT `any`, so the result stays typed at the
 * boundary and no `no-explicit-any` lint error is added: one narrow structural cast
 * of the client, and `RawRow` below is the contract with the RPC. If the generated
 * types are ever regenerated this whole shim deletes cleanly.
 */
type RpcCaller = (
  fn: string,
  args: Record<string, unknown>,
) => Promise<{ data: unknown; error: { message?: string } | null }>;

const callRpc: RpcCaller = (fn, args) =>
  (supabase as unknown as { rpc: RpcCaller }).rpc(fn, args);

interface RawRow {
  node_id: string | null;
  echelon: string | null;
  node_type: string | null;
  bom_depth: number | null;
  supply_tier: number | null;
  plant_name: string | null;
  label: string | null;
  location_text: string | null;
  longitude: number | null;
  latitude: number | null;
}

function toTyped(row: RawRow): TypedNode | null {
  const id = row.node_id?.trim();
  if (!id) return null;
  return {
    id,
    label: row.label?.trim() || id,
    // `echelon` only. `node_type` is NOT a fallback: it is the legacy vocabulary
    // DERIVED from the same rule, so reading it when `echelon` is null would
    // return a value the same rule declined to give — a substitution dressed as a
    // default. A null echelon is reported as one.
    echelon: asEchelon(row.echelon),
    bomDepth: row.bom_depth ?? null,
    supplyTier: row.supply_tier ?? null,
    plantName: row.plant_name ?? null,
    locationText: row.location_text ?? null,
    longitude: row.longitude ?? null,
    latitude: row.latitude ?? null,
  };
}

/**
 * The typed nodes of one project.
 *
 * Returns an empty set with `loading: false` and no error when there is no project
 * or no user — not an error, because "nothing selected" is not a failure, and a
 * page that shows an error for it teaches its users to ignore errors.
 */
export function useGraphNodes(
  projectId: string | null | undefined,
  user: { id: string; email?: string | null } | null | undefined,
): GraphNodesState {
  const [nodes, setNodes] = useState<TypedNode[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [tick, setTick] = useState(0);

  const refresh = useCallback(() => setTick((t) => t + 1), []);

  useEffect(() => {
    if (!projectId || !user?.id) {
      setNodes([]);
      setError(null);
      setLoading(false);
      return;
    }

    let cancelled = false;
    setLoading(true);
    setError(null);

    void (async () => {
      const { data, error: rpcError } = await callRpc('get_graph_nodes', {
        p_project_id: projectId,
        p_user_id: user.id,
        p_user_email: user.email ?? '',
      });

      if (cancelled) return;

      if (rpcError) {
        // The message is kept, not swallowed into a toast and lost. §4 D3 is what
        // swallowing one costs: a branch that had never executed, for a table that
        // had never existed, discovered by reading rather than by a report.
        setError(rpcError.message ?? 'get_graph_nodes failed');
        setNodes([]);
        setLoading(false);
        return;
      }

      const rows = ((data ?? []) as RawRow[]).map(toTyped).filter((n): n is TypedNode => n !== null);
      setNodes(rows);
      setLoading(false);
    })();

    return () => {
      cancelled = true;
    };
  }, [projectId, user?.id, user?.email, tick]);

  return {
    nodes,
    byId: new Map(nodes.map((n) => [n.id, n])),
    loading,
    error,
    untypedCount: nodes.filter((n) => n.echelon === null || n.echelon === 'unknown').length,
    refresh,
  };
}
