// Audit: every double-quoted string in handoff/PAGES.md is a claim that the
// product says exactly that. This checks each one against the live demo.
//
// Run it inside a run_script call (it uses readFile/saveFile/log), or port the
// body to node with fs.readFileSync. Output: handoff/AUDIT.md.
//
// Excluded from the check, deliberately:
//   SKIP_CLASS  Tailwind class strings — repo code, verified against the
//               repository, not the demo.
//   INVENTED    strings the book quotes in order to say they were WRONG and
//               were removed.
//   COMPOSED    labels built at runtime (count + noun), which no literal search
//               can match. Each was verified by reading the expression that
//               builds it; the source expression is recorded beside it here so
//               the claim is still checkable by hand.
//   GENERIC     a single ordinary word in prose.

const SKIP_CLASS = /(^|\s)(md:|w-\[|h-\[|flex |grid |hidden |min-w-0|shrink-0|box-content|items-|gap-|px-|py-|-m\[|-mx|calc\()/;

const INVENTED = [
  'Pending approval',        // §19 — the real model is is_active
  'read, run',               // §21 — not a real scope
  'read, admin',             // §21 — not a real scope
];

const COMPOSED = {
  'Showing 10 of 12': "viewerMoreLine: 'Showing ' + vShown.length + ' of ' + vRowCount + ' — raise the row limit to see more.'",
  'Showing 10 of 12 — raise the row limit to see more.': 'same expression as above',
  '3 rows selected': "selectionLabel: selIds.length + ' rows selected'",
  '1 row selected': "selectionLabel: selIds.length + ' row selected' (singular branch)",
  'Apply a patch to 3 selected rows.': "bulkSubtitle: 'Apply a patch to ' + selIds.length + ' selected rows.'",
  'Acknowledge 2 warnings': "ackAllLabel: 'Acknowledge ' + warnCount + ' warnings'",
  'Run rejected — 3 blocking gaps': "blockTitle: 'Run rejected — ' + blockCount + ' blocking gap' + (s)",
  'Tronico EMS · Gemini 2.5 Flash · Ask': "setupLabel: proj + ' · ' + mdl + ' · ' + (mode === 'review' ? 'Review' : 'Ask')",
  'Empty fields are skipped so the override stays sparse': 'repo string in BulkEditDialog.tsx, not demo copy — labelled as such in the entry',
};

const GENERIC = /^[A-Za-z][A-Za-z' -]{0,14}$/;

const MAP = {
  '01': ['isLanding'], '02': ['isAuth'], '03': ['isAbout'], '04': ['isHome'],
  '05': ['isDetail'], '06': ['viewerOpen'], '07': ['erpOpen'], '08': ['isDetail'],
  '09': ['nodeOpen'], '10': ['isDetail'], '11': ['isPolicies'],
  '12': ['isPolicies', 'bulkOpen'], '13': ['auxOpen', 'isLab'], '14': ['isLab'],
  '15': ['isLab'], '16': ['isAi'], '17': ['piSheetOpen'], '18': ['isMore'],
  '19': ['isAdmin'], '20': ['isAdmin'], '21': ['devOpen', 'mintedOpen'],
  '22': ['docsOpen'], '23': ['profileOpen'], '24': ['forbiddenOpen'], '25': ['isDetail'],
};

const norm = (s) => s
  .replace(/&amp;/g, '&').replace(/&rsquo;/g, '\u2019').replace(/&gt;/g, '>').replace(/&lt;/g, '<')
  .replace(/[\u2018\u2019]/g, "'").replace(/[\u201c\u201d]/g, '"')
  .replace(/\s+/g, ' ').trim();

export async function audit({ readFile, saveFile, log }) {
  const demo = await readFile('SuReSuite Live Demo.dc.html');
  const md = await readFile('handoff/PAGES.md');
  const D = norm(demo);

  const lines = demo.split('\n');
  const marks = [];
  lines.forEach((l, i) => {
    const m = l.match(/^      <sc-if value="\{\{ (\w+) \}\}"/);
    if (m) marks.push({ name: m[1], start: i });
  });
  marks.forEach((m, i) => { m.end = i + 1 < marks.length ? marks[i + 1].start : m.start + 220; });
  const blockOf = (n) => {
    const m = marks.find((x) => x.name === n);
    return m ? norm(lines.slice(m.start, m.end).join('\n')) : '';
  };

  const entries = md.split(/\n## /).slice(1).map((chunk) => ({
    head: chunk.split('\n')[0],
    num: (chunk.match(/^(\d+)/) || [])[1],
    text: chunk,
  }));

  let tot = 0, onScreen = 0, other = 0;
  const bad = [], detail = [], composedHits = [];

  entries.forEach((e) => {
    const scope = (MAP[e.num] || []).map(blockOf).join(' ');
    const quotes = [...new Set([...e.text.matchAll(/"([^"\n]{4,140})"/g)].map((m) => norm(m[1])))];
    const res = [];
    quotes.forEach((q) => {
      if (SKIP_CLASS.test(q) || INVENTED.includes(q) || GENERIC.test(q)) return;
      if (COMPOSED[q]) { composedHits.push({ head: e.head, q, src: COMPOSED[q] }); return; }
      tot++;
      if (scope.includes(q)) { onScreen++; return; }
      if (D.includes(q)) { other++; res.push({ q, v: 'other screen' }); return; }
      bad.push({ head: e.head, q });
      res.push({ q, v: 'NOT IN DEMO' });
    });
    if (res.length) detail.push({ head: e.head, res });
  });

  const ph = [...new Set([...demo.matchAll(/(Name to add|TBD|Lorem ipsum|coming soon|to be added)/gi)]
    .map((m) => 'line ' + demo.slice(0, m.index).split('\n').length + ' — ' + m[1]))];

  let rep = '# Audit — every quoted claim in the page book, checked against the demo\n\n';
  rep += 'Generated by `handoff/audit-pages.mjs`. Each double-quoted string in\n';
  rep += '`handoff/PAGES.md` is a claim that the product says exactly that.\n\n';
  rep += '## Result\n\n';
  rep += '- literal claims checked: ' + tot + '\n';
  rep += '- found on the screen the entry is about: ' + onScreen + '\n';
  rep += '- found in the demo but on another screen: ' + other + '\n';
  rep += '- **not in the demo at all: ' + bad.length + '**\n';
  rep += '- runtime-composed labels, checked by reading the expression: ' + composedHits.length + '\n\n';

  if (bad.length) {
    rep += '## Failures — fix these\n\n';
    bad.forEach((b) => { rep += '- ' + b.head + ' — "' + b.q + '"\n'; });
    rep += '\n';
  } else {
    rep += 'No failures: every literal claim resolves to a string in the demo.\n\n';
  }

  if (detail.length) {
    rep += '## Claims found on another screen\n\n';
    rep += 'Not necessarily wrong — shared chrome and cross-screen copy land here —\n';
    rep += 'but each one is worth confirming the entry attributes it correctly.\n\n';
    detail.forEach((d) => {
      rep += '### ' + d.head + '\n\n';
      d.res.forEach((x) => { rep += '- **' + x.v + '** — "' + x.q + '"\n'; });
      rep += '\n';
    });
  }

  rep += '## Runtime-composed labels\n\n';
  rep += 'A label built from a count can never match a literal search. Each is quoted\n';
  rep += 'in the book in its rendered form; the expression that builds it is here.\n\n';
  composedHits.forEach((c) => { rep += '- "' + c.q + '" — `' + c.src + '`\n'; });
  rep += '\n## Unfinished content in the demo\n\n';
  rep += (ph.length ? ph.map((s) => '- ' + s).join('\n') : 'none found') + '\n';

  await saveFile('handoff/AUDIT.md', rep);
  log('checked ' + tot + ' | on-screen ' + onScreen + ' | other screen ' + other + ' | NOT IN DEMO ' + bad.length);
  return bad;
}
