"""Generate the reference docs from the registry (Part IX §9.6).

Pydantic models are canonical: the policy catalog, variable dictionary,
pipeline contract and KPI table below are RENDERED, never hand-edited.
``--check`` (the docs CI gate) fails when the committed pages drift from
the code — an undocumented parameter therefore fails the build.

Usage:
    python scripts/gen_docs.py            # (re)write docs/reference/*
    python scripts/gen_docs.py --check    # CI gate
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from scsim import ENGINE_VERSION
from scsim.io.registry_export import build_registry

DOCS = Path(__file__).resolve().parents[1] / "docs" / "reference"

HEADER = (
    "<!-- GENERATED by scripts/gen_docs.py from the scsim registry "
    f"(engine {ENGINE_VERSION}). Do not edit by hand: the docs CI gate "
    "(gen_docs.py --check) fails on drift. -->\n\n"
)

STATUS_BADGE = {"implemented": "✅ implemented", "planned": "🧩 planned"}


def _fmt_default(prop: dict[str, Any]) -> str:
    if "default" in prop:
        d = prop["default"]
        if isinstance(d, dict):
            return ", ".join(f"{k}={v}" for k, v in d.items())
        return repr(d) if d is not None else "—"
    return "required" if prop.get("_required") else "—"


def _fmt_range(prop: dict[str, Any]) -> str:
    if prop.get("range"):
        return str(prop["range"])
    lo = prop.get("minimum", prop.get("exclusiveMinimum"))
    hi = prop.get("maximum", prop.get("exclusiveMaximum"))
    if lo is not None or hi is not None:
        return f"[{lo if lo is not None else '−∞'}, {hi if hi is not None else '∞'}]"
    if "enum" in prop:
        return "{" + ", ".join(map(str, prop["enum"])) + "}"
    if "$ref" in prop or "allOf" in prop or "anyOf" in prop:
        return "see schema"
    return "—"


def _resolve(prop: dict[str, Any], defs: dict[str, Any]) -> dict[str, Any]:
    """Inline single-$ref / allOf-of-one so enums and metadata surface."""
    merged = dict(prop)
    targets = []
    if "$ref" in prop:
        targets = [prop["$ref"]]
    elif "allOf" in prop and len(prop["allOf"]) == 1 and "$ref" in prop["allOf"][0]:
        targets = [prop["allOf"][0]["$ref"]]
    for ref in targets:
        name = ref.rsplit("/", 1)[-1]
        target = defs.get(name, {})
        merged = {**target, **{k: v for k, v in merged.items() if k not in ("$ref", "allOf")}}
    return merged


def _params_table(schema: dict[str, Any]) -> list[str]:
    props = schema.get("properties", {})
    defs = schema.get("$defs", {})
    required = set(schema.get("required", []))
    if not props:
        return ["_No parameters._", ""]
    out = [
        "| Parameter | Unit | Scope | Default | Range | Notes |",
        "|---|---|---|---|---|---|",
    ]
    for name, raw in props.items():
        prop = _resolve(raw, defs)
        if name in required:
            prop["_required"] = True
        notes = prop.get("notes", "") or prop.get("description", "")
        out.append(
            f"| `{name}` | {prop.get('unit', '—')} | {prop.get('scope', '—')} "
            f"| {_fmt_default(prop)} | {_fmt_range(prop)} | {notes} |"
        )
    out.append("")
    return out


def render_policies(reg: dict[str, Any]) -> str:
    lines = [HEADER, "# Policy catalog (Part IV)\n"]
    lines.append(
        "Twenty-two policies in five classes. ✅ = validated manuscript core, runnable "
        "today; 🧩 = governed extension — full parameter schema in the registry, engine "
        "lands at the listed milestone (compiling one raises a clear error, never a "
        "silent no-op).\n"
    )
    lines.append("| Ref | id | Stage | Class | Constraint | Status |")
    lines.append("|---|---|---|---|---|---|")
    for p in reg["policies"]:
        lines.append(
            f"| {p['catalog_ref']} | [`{p['id']}`](#{p['id']}) | {p['stage']} "
            f"| {p['strategy_class']} | {p['constraint_targeted'] or '—'} "
            f"| {STATUS_BADGE[p['status']]} |"
        )
    lines.append("")
    for p in reg["policies"]:
        lines.append(f"## `{p['id']}`\n")
        lines.append(f"**{p['catalog_ref']}** · {p['stage']} · {p['strategy_class']} · "
                     f"constraint: {p['constraint_targeted'] or '—'} · "
                     f"{STATUS_BADGE[p['status']]}"
                     + (f" · lands in {p['milestone']}" if p["milestone"] else "")
                     + (" · requires pre-deployment" if p["requires_predeployment"] else ""))
        lines.append("")
        lines.append(p["summary"])
        lines.append("")
        if p["hooks"]:
            lines.append("**Hooks**\n")
            lines.append("| Phase | Priority | Reads | Writes | Resolution |")
            lines.append("|---|---|---|---|---|")
            for h in p["hooks"]:
                lines.append(
                    f"| {h['phase']} | {h['priority']} | {', '.join(h['reads']) or '—'} "
                    f"| {', '.join(h['writes']) or '—'} | {h['resolution'] or '—'} |"
                )
            lines.append("")
        lines.append("**Parameters**\n")
        lines.extend(_params_table(p["params_schema"]))
    return "\n".join(lines)


def render_variables(reg: dict[str, Any]) -> str:
    lines = [HEADER, "# Variable dictionary (Part III)\n"]
    lines.append(
        "Rendered from the canonical Pydantic entities. Scope legend: G global · "
        "P product · M material · S supplier · SM supplier×material · E edge · "
        "C customer.\n"
    )
    titles = {
        "simulation_settings": "§3.0 Global simulation & statistics",
        "product": "§3.1–3.3 Customer demand, plant products & fulfillment mode",
        "customer": "§3.1 Customer segments",
        "bom_line": "§3.2 Bill of materials",
        "material": "§3.4 Material inventory",
        "supplier": "§3.5 Supplier echelon",
        "supplier_link": "§3.5 Qualified (supplier × material) sources",
        "lane": "§3.6 Transport edges (behavior-neutral defaults)",
        "disruption_event": "§3.7 Disruption event model",
    }
    for key in ("simulation_settings", "product", "customer", "bom_line", "material",
                "supplier", "supplier_link", "lane", "disruption_event"):
        schema = reg["entities"][key]
        lines.append(f"## {titles[key]} — `{key}`\n")
        if schema.get("description"):
            lines.append(schema["description"].strip().split("\n")[0] + "\n")
        lines.extend(_params_table(schema))
    return "\n".join(lines)


def render_pipeline(reg: dict[str, Any]) -> str:
    lines = [HEADER, "# Phase pipeline contract (Part IX §9.1)\n"]
    lines.append(
        "The weekly cycle is data, not code. Each phase owns its transient write-"
        "contract; persistent `state.*` keys list their authorized writer phases. "
        "This page mirrors `scsim/pipeline_schema.json` — the snapshot test fails "
        "the build on accidental drift (Tier-3 changes re-freeze it with an ADR).\n"
    )
    lines.append("| Phase | Name | Owns (transient) | Description |")
    lines.append("|---|---|---|---|")
    for ph in reg["pipeline"]["phases"]:
        lines.append(f"| {ph['id']} | {ph['name']} | {', '.join(ph['owns']) or '—'} "
                     f"| {ph['description']} |")
    lines.append("")
    lines.append("## Persistent state writers\n")
    lines.append("| Key | Writable from |")
    lines.append("|---|---|")
    for key, phases in reg["pipeline"]["persistent_state"].items():
        lines.append(f"| `{key}` | {', '.join(phases)} |")
    lines.append("")
    return "\n".join(lines)


def render_kpis(reg: dict[str, Any]) -> str:
    lines = [HEADER, "# KPI dictionary (Part V)\n"]
    lines.append("| KPI | Symbol | Definition | Unit |")
    lines.append("|---|---|---|---|")
    for k in reg["kpis"]:
        lines.append(f"| `{k['name']}` | {k['symbol']} | {k['definition']} | {k['unit']} |")
    lines.append("")
    return "\n".join(lines)


PAGES = {
    "policies.md": render_policies,
    "variables.md": render_variables,
    "pipeline.md": render_pipeline,
    "kpis.md": render_kpis,
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail (exit 1) if committed docs drift from the registry")
    args = ap.parse_args()

    reg = build_registry()
    DOCS.mkdir(parents=True, exist_ok=True)
    drifted = []
    for filename, renderer in PAGES.items():
        content = renderer(reg)
        path = DOCS / filename
        if args.check:
            if not path.exists() or path.read_text() != content:
                drifted.append(filename)
        else:
            path.write_text(content)
            print(f"wrote {path.relative_to(DOCS.parents[1])}")
    if args.check and drifted:
        print(f"DOCS DRIFT: {drifted} — run `python scripts/gen_docs.py` and commit",
              file=sys.stderr)
        return 1
    if args.check:
        print("docs reference pages are in sync with the registry")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
