-- GENERATED by scripts/data-contract/gen-unit-sql.mjs from
-- supabase/functions/_shared/grading.ts::UNIT_DAYS. Do not edit by hand: the data
-- contract CI gate (`npm run contract:units -- --check`) fails on drift.
--
-- Phase 1 / WP 1.3 / D10 — ONE unit table.
--
-- Before this migration the platform carried three conversions that disagreed.
-- The third lived in the `sc_nodes` view as three ILIKE branches and an ELSE, so
-- a row quoted in QUARTERS matched nothing, fell to ELSE and was read as weekly:
-- a 13x error on that product's demand, silently. Its constants (4.345, 52.18)
-- also disagreed with the canonical 30.4375/7 and 365.25/7.
--
-- `unit_days` below is rendered from the TypeScript table; SQL no longer holds an
-- opinion about what a quarter is.

CREATE OR REPLACE FUNCTION public.unit_days(unit text)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
SET search_path = public
AS $$
  SELECT CASE lower(btrim(coalesce(unit, '')))
    WHEN 'day' THEN 1::numeric
    WHEN 'days' THEN 1::numeric
    WHEN 'd' THEN 1::numeric
    WHEN 'daily' THEN 1::numeric
    WHEN 'week' THEN 7::numeric
    WHEN 'weeks' THEN 7::numeric
    WHEN 'wk' THEN 7::numeric
    WHEN 'w' THEN 7::numeric
    WHEN 'weekly' THEN 7::numeric
    WHEN 'month' THEN 30.4375::numeric
    WHEN 'months' THEN 30.4375::numeric
    WHEN 'mo' THEN 30.4375::numeric
    WHEN 'm' THEN 30.4375::numeric
    WHEN 'monthly' THEN 30.4375::numeric
    WHEN 'quarter' THEN 91.3125::numeric
    WHEN 'quarters' THEN 91.3125::numeric
    WHEN 'quarterly' THEN 91.3125::numeric
    WHEN 'year' THEN 365.25::numeric
    WHEN 'years' THEN 365.25::numeric
    WHEN 'yr' THEN 365.25::numeric
    WHEN 'y' THEN 365.25::numeric
    WHEN 'yearly' THEN 365.25::numeric
    WHEN 'annual' THEN 365.25::numeric
    WHEN 'annually' THEN 365.25::numeric
    ELSE NULL::numeric
  END;
$$;

COMMENT ON FUNCTION public.unit_days(text) IS
  'Days in one period of `unit`, or NULL when the unit is unrecognised. Generated '
  'from grading.ts::UNIT_DAYS — the one unit table (PLAN.md §4 D10, invariant I3).';

-- Quantity per `unit`-period -> quantity per week. Mirrors
-- grading.ts::rateToWeekly and project_map.py::_rate_to_weekly, including the
-- default: an unrecognised or missing unit is read on a 7-day basis, i.e. the
-- value is already weekly.
CREATE OR REPLACE FUNCTION public.rate_to_weekly(value numeric, unit text, default_days numeric DEFAULT 7)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
SET search_path = public
AS $$
  SELECT value * 7.0 / COALESCE(NULLIF(public.unit_days(unit), 0), default_days);
$$;

COMMENT ON FUNCTION public.rate_to_weekly(numeric, text, numeric) IS
  'A rate quoted per `unit` expressed per week. Mirrors grading.ts::rateToWeekly.';

-- A DURATION of `value` `unit`s expressed in weeks. Mirrors
-- project_map.py::_duration_to_weeks. Note the direction: a duration of 1 month
-- is ~4.35 weeks, while a rate of 1 per month is ~0.23 per week.
CREATE OR REPLACE FUNCTION public.duration_to_weeks(value numeric, unit text, default_days numeric DEFAULT 7)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
SET search_path = public
AS $$
  SELECT value * COALESCE(NULLIF(public.unit_days(unit), 0), default_days) / 7.0;
$$;

COMMENT ON FUNCTION public.duration_to_weeks(numeric, text, numeric) IS
  'A duration of `value` `unit`s expressed in weeks. Mirrors project_map.py::_duration_to_weeks.';

GRANT EXECUTE ON FUNCTION public.unit_days(text) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.rate_to_weekly(numeric, text, numeric) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.duration_to_weeks(numeric, text, numeric) TO authenticated, anon, service_role;

-- ── sc_nodes: delegate, and weight the price aggregate the way the engine does ──
--
-- Two changes, both to the `agg` sub-select:
--
--   1. weekly_demand calls rate_to_weekly() instead of restating the table.
--   2. the price aggregate now matches grading.ts::demandWeightedSellPrice:
--      weight by WEEKLY volume (not raw volume, which mixes periods exactly as
--      D2 did), skip rows with no price rather than averaging a zero in, and
--      drop the `ELSE MAX(unit_price)` fallback. MAX() is not an estimate of
--      anything — for a product sold to three customers at 8, 10 and 30 with no
--      volumes, it answered 30.
CREATE OR REPLACE VIEW public.sc_nodes AS
SELECT 'supplier:' || s.supplier_id AS id, s.project_id, COALESCE(s.name, s.supplier_id) AS name,
       'supplier' AS node_type, NULL::numeric AS weekly_demand, NULL::numeric AS unit_price,
       NULL::numeric AS capacity_units_per_day, 1.0::numeric AS yield_rate,
       s.capacity_per_week
FROM public.suppliers s
UNION ALL
SELECT 'material:' || m.material_id, m.project_id, COALESCE(m.name, m.material_id),
       'material', NULL::numeric, m.cost, NULL::numeric, 1.0::numeric, NULL::numeric
FROM public.materials m
UNION ALL
SELECT 'product:' || p.product_id, p.project_id, COALESCE(p.name, p.product_id),
       'product',
       COALESCE(p.demand_mean, agg.weekly_demand),
       COALESCE(p.sell_price, agg.unit_price),
       p.production_capacity, 1.0::numeric, NULL::numeric
FROM public.products p
LEFT JOIN (
  SELECT project_id, product_id,
         SUM(public.rate_to_weekly(COALESCE(volume, 0), time_unit)) AS weekly_demand,
         CASE
           WHEN SUM(CASE WHEN COALESCE(unit_price, 0) <> 0
                         THEN GREATEST(public.rate_to_weekly(COALESCE(volume, 0), time_unit), 1e-9)
                         ELSE 0 END) > 0
           THEN SUM(CASE WHEN COALESCE(unit_price, 0) <> 0
                         THEN unit_price * GREATEST(public.rate_to_weekly(COALESCE(volume, 0), time_unit), 1e-9)
                         ELSE 0 END)
              / SUM(CASE WHEN COALESCE(unit_price, 0) <> 0
                         THEN GREATEST(public.rate_to_weekly(COALESCE(volume, 0), time_unit), 1e-9)
                         ELSE 0 END)
           ELSE NULL::numeric
         END AS unit_price
  FROM public.outbound_logistics GROUP BY project_id, product_id
) agg ON agg.project_id = p.project_id AND agg.product_id = p.product_id
UNION ALL
SELECT 'customer:' || o.customer_id, o.project_id, o.customer_id,
       'customer', NULL::numeric, NULL::numeric, NULL::numeric, 1.0::numeric, NULL::numeric
FROM public.outbound_logistics o GROUP BY o.project_id, o.customer_id;

GRANT SELECT ON public.sc_nodes TO authenticated, anon, service_role;
